In [1]:
# filtering out warnings
import warnings
warnings.filterwarnings('ignore')

import pandas as pd

In [2]:
# importing the dataset
data=pd.read_csv('messy_data.csv',index_col=[0])
data.head(10)

,ID,Name,Age,Email,Join Date,Salary,Department
0,1e407ff9-6255-489d-a0de-34135d4f74bd,Hunter Thomas,25.0,xlopez@hotmail.com,NaN,88552.000000,Sales
1,379f55b8-87d5-4739-a146-7400b78c24d1,Jeremy Irwin,90.0,Jillian Jenkins,2022-07-07,139227.000000,NaN
2,18261368-dfa1-47f0-afc6-bddf45926b07,Jennifer Hammondquickly,66.0,jscottgreen.biz,2023-11-21,65550.000000,Engineering
3,ae7cf7cf-17cf-4c8b-9c44-4f61a9a238e5,Sydney Taylorso,39.0,luke56gonzalez.com,2021-11-05,139932.000000,SupportJ
4,14ed3e6a-e0f5-4bbe-8d93-8665267f5c90,Julia Lee,71.0,figueroakayla@yahoo.com,NaN,143456.000000,Marketing
5,f92ea13f-24d3-4792-91e4-5b0e07d90c2c,Lisa Bailey,81.0,milleryvonne@fowler-york.com,15/10/2016,123018.000000,SupportE
6,c4892dbb-2554-4ce1-8f11-f6597d7f6782,Patricia Brown DVM,66.0,pperkinshotmail.com,17/09/2020,77311.000000,HR
7,465e625b-f924-4061-8356-c7e3130f7118,Derek Murphy,38.0,josephrobertsongmail.com,2021-01-12,NaN,Support
8,12cc2f16-d641-402e-b22b-3332bafc4f1d,NaN,71.0,andrew74@hotmail.com,2022-02-12,83354.000000,Sales
9,d06f507d-62e5-4bd6-a252-4e60e109d324,Jay Fisher,44.0,denisemaynard@jordan.com,2022-12-08,37701.725993,HR

In [3]:
data.tail(10)

,ID,Name,Age,Email,Join Date,Salary,Department
3317,10c26512-ce3a-4387-b71a-47768503562e,Kimberly Cummings,54.0,rmccoy@hall.com,2020-06-11,60950.500220,Marketing
9603,612011e6-101d-4ee2-bbca-16a5056d8217,Jeffrey Elliottnation,72.0,jpatterson@wise.org,2021-08-05,50510.777098,Support
7429,749e71e0-f852-4749-bae3-b59b9c5a9e77,NaN,31.0,kingcharles@hotmail.com,2020-11-28,88530.000000,Marketing
9510,796f8c0b-15a4-475c-bb02-ac892df0c746,Shelley Hopkinslive,79.0,Michael Walker,25/12/1992,47809.000000,HR
3978,6714ff24-3600-4c6e-8eed-5b4224bd9e44,Karen Wells,29.0,cheryllewis@hotmail.com,NaN,147555.000000,Engineering
6523,07c223be-03e6-4f70-a2b5-86df778cc61a,NaN,NaN,NaN,NaN,NaN,NaN
9785,da8a6bbc-5026-4630-848d-f64e80dac56c,Steven Armstrong,38.0,molly89gmail.com,2021-06-24,NaN,Sales
7826,ed19c966-d6d8-4047-b410-b6e595a39340,Stephanie Riossell,NaN,robert96@pollard-frye.com,15/08/2006,122609.594149,HR
7648,783b36b4-d09f-46c9-8a52-7ff96b80863e,Bonnie Benitez,37.0,roypark@warren.net,2020-10-09,147322.005171,Support
7107,fc25a38a-5747-46eb-b6d3-7173f8255809,Caroline Ochoa,53.0,cdavis@hodges.com,2023-08-10,149224.000000,Support

In [4]:
data.shape

(11000, 7)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11000 entries, 0 to 7107
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          11000 non-null  object
 1   Name        8667 non-null   object
 2   Age         9253 non-null   float64
 3   Email       9731 non-null   object
 4   Join Date   8808 non-null   object
 5   Salary      8761 non-null   float64
 6   Department  8745 non-null   object
dtypes: float64(2), object(5)
memory usage: 687.5+ KB

In [6]:
data['Salary'] = data['Salary'].round(2)

In [7]:
data.describe()

               Age         Salary
count  9253.000000    8761.000000
mean     54.162650   89886.585028
std      21.072919   34896.320124
min      18.000000   24655.140000
25%      36.000000   59723.840000
50%      54.000000   89241.000000
75%      72.000000  119491.000000
max      90.000000  176156.210000

In [8]:
# dropping the rows with only ID value
data=data.dropna(subset=['Name','Age','Email','Join Date','Salary','Department'],how='all')
data.shape

(9731, 7)

In [9]:
data=data.drop_duplicates()

In [10]:
data.shape

(9617, 7)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9617 entries, 0 to 7648
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          9617 non-null   object
 1   Name        8579 non-null   object
 2   Age         9145 non-null   float64
 3   Email       9617 non-null   object
 4   Join Date   8707 non-null   object
 5   Salary      8661 non-null   float64
 6   Department  8647 non-null   object
dtypes: float64(2), object(5)
memory usage: 601.1+ KB

In [12]:
data['ID'].nunique()

8908

In [13]:
data["ID"].value_counts()

468d3baa-8db4-477d-8090-e7399b2820a7    2
5af13486-4717-401e-8c1e-d24608b41630    2
2848b845-6ea0-4815-a3d4-0aaa0d9f7ecd    2
d6d14a61-ea06-4ce0-bc6d-a5896c470479    2
9e510af1-e06c-4a84-82db-c58bcb153962    2
                                       ..
e2cec4e1-5116-4fcb-b838-a518d61f6ec7    1
db215936-dbf5-444f-89de-78c575d5e64c    1
c624e85b-eb35-4220-95cc-ec949f10ad33    1
18a62e23-1caa-4bee-adcc-e07d9751ecbd    1
ae6eee4d-ca8f-4932-96f1-487230875968    1
Name: ID, Length: 8908, dtype: int64

In [14]:
# function to check the duplicate values if present
def duplicate_value():
    duplicate_rows=data[data.duplicated(subset='ID',keep=False)]
    grouped_duplicates=duplicate_rows.groupby("ID")

    for id, group in grouped_duplicates:
        print(f"Duplicate rows for ID {id}:")
        print(group)
        print("\n")

In [15]:
data['Department'].unique()

array(['Sales', nan, 'Engineering', 'SupportJ', 'Marketing', 'SupportE',
       'HR', 'Support', 'HRC', 'SalesA', 'SalesX', 'Supportu',
       'Engineeringi', 'MarketingR', 'Salesw', 'SalesK', 'MarketingU',
       'Salesi', 'HRa', 'SalesG', 'Supporty', 'SalesN', 'Marketinge',
       'Marketingv', 'HRv', 'SalesM', 'EngineeringL', 'MarketingQ', 'HRs',
       'SalesW', 'Supportj', 'Salesd', 'Marketingu', 'Engineeringj',
       'SalesU', 'HRO', 'MarketingH', 'Salesj', 'Saleso', 'SalesZ',
       'Engineeringe', 'MarketingF', 'Marketingr', 'Engineeringm', 'HRW',
       'HRt', 'HRz', 'Engineeringp', 'HRF', 'EngineeringS', 'SupportW',
       'EngineeringT', 'SalesC', 'SalesB', 'SupportC', 'SalesY',
       'Marketingn', 'EngineeringK', 'Marketingz', 'HRo', 'SupportB',
       'HRi', 'Salest', 'Supportg', 'Supporta', 'HRn', 'SupportQ',
       'Salesr', 'EngineeringG', 'Supportm', 'Supporto', 'EngineeringH',
       'Marketingw', 'EngineeringM', 'Supportz', 'HRr', 'Salesy',
       'MarketingD', 'HRE', 'Marketingm', 'HRw', 'Marketingo', 'Supportk',
       'MarketingN', 'SupportS', 'EngineeringD', 'Marketingp', 'Salesl',
       'MarketingI', 'MarketingL', 'SupportT', 'Engineeringn',
       'MarketingO', 'SalesF', 'Salesz', 'Marketingt', 'Engineeringv',
       'HRL', 'HRI', 'EngineeringR', 'HRD', 'Marketingk', 'HRQ', 'Salese',
       'Saless', 'Marketingi', 'Salesn', 'Engineeringl', 'SalesE', 'HRy',
       'EngineeringE', 'SalesD', 'HRm', 'Engineerings', 'SupportF',
       'Marketingy', 'MarketingG', 'SalesI', 'Salesu', 'Engineeringg',
       'EngineeringQ', 'MarketingE', 'SupportA', 'Engineeringq',
       'EngineeringA', 'Supporte', 'Engineeringu', 'EngineeringO',
       'SalesS', 'Supportv', 'HRK', 'Engineeringb', 'SalesV', 'HRT',
       'SupportY', 'SalesQ', 'MarketingX', 'Supportp', 'Marketingf',
       'HRU', 'HRp', 'Salesq', 'HRg', 'Marketingl', 'EngineeringV',
       'Engineeringt', 'SupportO', 'SalesJ', 'EngineeringX',
       'Engineeringc', 'Marketingh', 'EngineeringC', 'Engineeringz',
       'HRP', 'Salesv', 'Engineeringk', 'SupportH', 'Salesk', 'Supporth',
       'SupportZ', 'Supportq', 'Supportr', 'HRJ', 'Supportd', 'HRZ',
       'MarketingZ', 'Salesc', 'EngineeringJ', 'Engineeringx', 'SalesR',
       'Engineeringh', 'Supportl', 'SupportX', 'Marketingg', 'SalesH',
       'MarketingC', 'SupportV', 'HRq', 'Marketingb', 'Supporti',
       'Supportw', 'SupportL', 'Marketings', 'Marketingq', 'HRM',
       'Supportt', 'HRX', 'HRl', 'EngineeringF', 'SupportP', 'HRf',
       'MarketingB', 'Engineeringf', 'EngineeringW', 'HRB',
       'Engineeringy', 'Marketinga', 'HRj', 'HRd', 'SupportI', 'HRA',
       'Marketingj', 'MarketingV', 'EngineeringI', 'HRY', 'EngineeringZ',
       'MarketingY', 'Marketingx', 'HRH', 'HRN', 'MarketingJ',
       'MarketingW', 'HRh', 'Supportb', 'SalesT', 'Supportn',
       'Engineeringa', 'SupportG', 'SalesO', 'SupportK', 'Engineeringd',
       'HRk', 'Marketingd', 'MarketingS', 'MarketingT', 'HRR',
       'Engineeringw', 'Salesg', 'HRb', 'SupportN', 'Marketingc',
       'EngineeringU', 'Supportx', 'Salesp', 'HRu', 'MarketingK',
       'SalesL', 'Salesx', 'SupportD', 'Supports', 'Salesm',
       'Engineeringr', 'HRe', 'SupportM', 'MarketingM', 'SupportR',
       'SupportU', 'Salesa', 'Salesf', 'Supportf', 'Salesh', 'Salesb',
       'EngineeringB', 'HRG', 'Engineeringo', 'EngineeringN', 'HRV',
       'HRS', 'SalesP', 'Supportc', 'HRx', 'EngineeringP', 'HRc',
       'MarketingP', 'MarketingA'], dtype=object)

In [16]:
# cleaning the department names
data['Department']=data['Department'].str.extract(r'^(HR|Engineering|Marketing|Sales|Support)')

In [17]:
data['Department'].unique()

array(['Sales', nan, 'Engineering', 'Support', 'Marketing', 'HR'],
      dtype=object)

In [18]:
data=data.drop_duplicates()

data.shape

(9552, 7)

In [19]:
# formatting the join date in the 'YYYY-MM-DD' format
data['Join Date']=pd.to_datetime(data['Join Date'],errors='coerce').dt.strftime('%Y-%m-%d')

In [20]:
data

,ID,Name,Age,Email,Join Date,Salary,Department
0,1e407ff9-6255-489d-a0de-34135d4f74bd,Hunter Thomas,25.0,xlopez@hotmail.com,NaN,88552.00,Sales
1,379f55b8-87d5-4739-a146-7400b78c24d1,Jeremy Irwin,90.0,Jillian Jenkins,2022-07-07,139227.00,NaN
2,18261368-dfa1-47f0-afc6-bddf45926b07,Jennifer Hammondquickly,66.0,jscottgreen.biz,2023-11-21,65550.00,Engineering
3,ae7cf7cf-17cf-4c8b-9c44-4f61a9a238e5,Sydney Taylorso,39.0,luke56gonzalez.com,2021-11-05,139932.00,Support
4,14ed3e6a-e0f5-4bbe-8d93-8665267f5c90,Julia Lee,71.0,figueroakayla@yahoo.com,NaN,143456.00,Marketing
...,...,...,...,...,...,...,...
7429,749e71e0-f852-4749-bae3-b59b9c5a9e77,NaN,31.0,kingcharles@hotmail.com,2020-11-28,88530.00,Marketing
9510,796f8c0b-15a4-475c-bb02-ac892df0c746,Shelley Hopkinslive,79.0,Michael Walker,1992-12-25,47809.00,HR
9785,da8a6bbc-5026-4630-848d-f64e80dac56c,Steven Armstrong,38.0,molly89gmail.com,2021-06-24,NaN,Sales
7826,ed19c966-d6d8-4047-b410-b6e595a39340,Stephanie Riossell,NaN,robert96@pollard-frye.com,2006-08-15,122609.59,HR
7648,783b36b4-d09f-46c9-8a52-7ff96b80863e,Bonnie Benitez,37.0,roypark@warren.net,2020-10-09,147322.01,Support

In [21]:
data=data.drop_duplicates()

data.shape

(9552, 7)

In [22]:
data.tail(5)

,ID,Name,Age,Email,Join Date,Salary,Department
7429,749e71e0-f852-4749-bae3-b59b9c5a9e77,NaN,31.0,kingcharles@hotmail.com,2020-11-28,88530.00,Marketing
9510,796f8c0b-15a4-475c-bb02-ac892df0c746,Shelley Hopkinslive,79.0,Michael Walker,1992-12-25,47809.00,HR
9785,da8a6bbc-5026-4630-848d-f64e80dac56c,Steven Armstrong,38.0,molly89gmail.com,2021-06-24,NaN,Sales
7826,ed19c966-d6d8-4047-b410-b6e595a39340,Stephanie Riossell,NaN,robert96@pollard-frye.com,2006-08-15,122609.59,HR
7648,783b36b4-d09f-46c9-8a52-7ff96b80863e,Bonnie Benitez,37.0,roypark@warren.net,2020-10-09,147322.01,Support

In [23]:
data['Name'].nunique()

7929

In [24]:
data['Email'] = data['Email'].str.lower()
data['Email'] = data['Email'].str.strip()

In [25]:
# function to fix the email format
import re
def fix_email_format(email):
    if pd.isna(email):  # Keep NaN values as is
        return None

    email = email.strip().lower()  # Trim spaces & lowercase
    
    # Regex pattern to capture missing "@" before common email providers
    pattern = r'([a-zA-Z0-9._%+-]+)(yahoo\.com|gmail\.com|hotmail\.com|outlook\.com)$'
    fixed_email = re.sub(pattern, r'\1@\2', email)  # Insert '@' before domain

    return fixed_email if '@' in fixed_email else None  # Ensure valid format

# Apply function to fix emails
data['Email'] = data['Email'].apply(fix_email_format)
def is_valid_email(email):
    pattern = r'^[a-zA-Z0-9._%+-]+@[gmail,hotmail,yahoo]+\.com'
    return bool(re.match(pattern, str(email)))

data['Email'] = data['Email'].apply(lambda x: x if is_valid_email(x) else None)

In [26]:
data.head(5)

,ID,Name,Age,Email,Join Date,Salary,Department
0,1e407ff9-6255-489d-a0de-34135d4f74bd,Hunter Thomas,25.0,xlopez@hotmail.com,NaN,88552.0,Sales
1,379f55b8-87d5-4739-a146-7400b78c24d1,Jeremy Irwin,90.0,None,2022-07-07,139227.0,NaN
2,18261368-dfa1-47f0-afc6-bddf45926b07,Jennifer Hammondquickly,66.0,None,2023-11-21,65550.0,Engineering
3,ae7cf7cf-17cf-4c8b-9c44-4f61a9a238e5,Sydney Taylorso,39.0,None,2021-11-05,139932.0,Support
4,14ed3e6a-e0f5-4bbe-8d93-8665267f5c90,Julia Lee,71.0,figueroakayla@yahoo.com,NaN,143456.0,Marketing

In [27]:
data.tail(5)

,ID,Name,Age,Email,Join Date,Salary,Department
7429,749e71e0-f852-4749-bae3-b59b9c5a9e77,NaN,31.0,kingcharles@hotmail.com,2020-11-28,88530.00,Marketing
9510,796f8c0b-15a4-475c-bb02-ac892df0c746,Shelley Hopkinslive,79.0,None,1992-12-25,47809.00,HR
9785,da8a6bbc-5026-4630-848d-f64e80dac56c,Steven Armstrong,38.0,molly89@gmail.com,2021-06-24,NaN,Sales
7826,ed19c966-d6d8-4047-b410-b6e595a39340,Stephanie Riossell,NaN,None,2006-08-15,122609.59,HR
7648,783b36b4-d09f-46c9-8a52-7ff96b80863e,Bonnie Benitez,37.0,None,2020-10-09,147322.01,Support

In [28]:
data['Email'].unique()

array(['xlopez@hotmail.com', None, 'figueroakayla@yahoo.com', ...,
       'nfranklin@yahoo.com', 'lmyers@gmail.com', 'cjones@yahoo.com'],
      dtype=object)

In [29]:
data=data.drop_duplicates()

data.shape

(9480, 7)

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9480 entries, 0 to 7648
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          9480 non-null   object
 1   Name        8465 non-null   object
 2   Age         9012 non-null   float64
 3   Email       4567 non-null   object
 4   Join Date   8592 non-null   object
 5   Salary      8542 non-null   float64
 6   Department  8516 non-null   object
dtypes: float64(2), object(5)
memory usage: 592.5+ KB

In [31]:
# function to clean the names
def clean_name(name):
    if pd.isna(name):  # Keep NaN values as is
        return None
    
    name = name.strip()  # Trim spaces
    name = re.sub(r'\b(Mr|Dr|Mrs|Ms|Miss|Prof)\.? ?', '', name, flags=re.IGNORECASE)  # Remove titles
    name = re.sub(r'[^a-zA-Z\s]', '', name)  # Remove special characters
    name = re.sub(r'([a-zA-Z]+)\1$', r'\1', name)  # Remove repeated last words (e.g., Huntercold -> Hunter)
    name_parts = name.split()  # Split into words

    if len(name_parts) >= 2:
        name = f"{name_parts[0]} {name_parts[1]}"  # Keep only first and last name
    else:
        name = name_parts[0] if name_parts else ''  # Handle single-word names
    
    return name.strip()  # Return cleaned name

# Apply function to clean names
data['Name'] = data['Name'].apply(clean_name)

In [32]:
data.shape

(9480, 7)

In [33]:
data

,ID,Name,Age,Email,Join Date,Salary,Department
0,1e407ff9-6255-489d-a0de-34135d4f74bd,Hunter Thomas,25.0,xlopez@hotmail.com,NaN,88552.00,Sales
1,379f55b8-87d5-4739-a146-7400b78c24d1,Jeremy Irwin,90.0,None,2022-07-07,139227.00,NaN
2,18261368-dfa1-47f0-afc6-bddf45926b07,Jennifer Hammondquickly,66.0,None,2023-11-21,65550.00,Engineering
3,ae7cf7cf-17cf-4c8b-9c44-4f61a9a238e5,Sydney Taylorso,39.0,None,2021-11-05,139932.00,Support
4,14ed3e6a-e0f5-4bbe-8d93-8665267f5c90,Julia Le,71.0,figueroakayla@yahoo.com,NaN,143456.00,Marketing
...,...,...,...,...,...,...,...
9603,612011e6-101d-4ee2-bbca-16a5056d8217,Jeffrey Elliottnation,72.0,None,2021-08-05,50510.78,Support
9510,796f8c0b-15a4-475c-bb02-ac892df0c746,Shelley Hopkinslive,79.0,None,1992-12-25,47809.00,HR
9785,da8a6bbc-5026-4630-848d-f64e80dac56c,Steven Armstrong,38.0,molly89@gmail.com,2021-06-24,NaN,Sales
7826,ed19c966-d6d8-4047-b410-b6e595a39340,Stephanie Riossel,NaN,None,2006-08-15,122609.59,HR
7648,783b36b4-d09f-46c9-8a52-7ff96b80863e,Bonnie Benitez,37.0,None,2020-10-09,147322.01,Support

In [34]:
duplicate_value()

Duplicate rows for ID 0053781e-61aa-423e-ae39-adc1ee24f24c:
                                        ID                 Name   Age Email  \
1009  0053781e-61aa-423e-ae39-adc1ee24f24c        Ronald Morgan  43.0  None
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morganlikely  43.0  None

       Join Date    Salary Department
1009  2020-02-23  140100.0  Marketing
1009  2022-01-02  140100.0  Marketing


Duplicate rows for ID 00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e:
                                        ID                Name   Age Email  \
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomasbudget  83.0  None
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e        Tammy Thomas  83.0  None

       Join Date   Salary Department
7942  1991-08-13  63500.0  Marketing
7942  2020-03-17  63500.0  Marketing


Duplicate rows for ID 00d23202-87b8-49bf-bec4-deea25ca43f4:
                                        ID                    Name   Age  \
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezsummer  41.0
9851  00d23202-87b8-49bf-bec4-deea25ca43f4    Kelsey Gutierrezwind  41.0

     Email Join Date    Salary Department
9851  None       NaN  36948.17         HR
9851  None       NaN  44371.00         HR


Duplicate rows for ID 019f2dce-1c6b-48a3-975a-b5fc0f524662:
                                        ID                      Name   Age  \
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662        Joshua Wagnerbegin  70.0
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerenvironment  70.0

     Email   Join Date     Salary Department
6302  None  2020-06-20  108294.68  Marketing
6302  None  2020-06-20  110313.00  Marketing


Duplicate rows for ID 02d6256d-a177-46b6-aaf8-6e18063336e5:
                                       ID  Name   Age                Email  \
939  02d6256d-a177-46b6-aaf8-6e18063336e5  None  21.0  melissa05@gmail.com
939  02d6256d-a177-46b6-aaf8-6e18063336e5  None  21.0  melissa05@gmail.com

      Join Date    Salary Department
939  2023-08-16  140138.0         HR
939  2006-07-10  140138.0         HR


Duplicate rows for ID 02db9c6e-d4fc-4321-9556-11b01bb12bb9:
                                       ID               Name   Age Email  \
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9     John Baileybad  49.0  None
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileysister  49.0  None

      Join Date  Salary Department
587  1989-01-08     NaN    Support
587  1970-06-19     NaN    Support


Duplicate rows for ID 02fae873-2e0a-4e1d-94d3-3de1d6476f31:
                                        ID            Name   Age  \
1483  02fae873-2e0a-4e1d-94d3-3de1d6476f31  Mike Woodsfact  31.0
1483  02fae873-2e0a-4e1d-94d3-3de1d6476f31      Mike Woods  31.0

                       Email   Join Date   Salary Department
1483  kathleenbell@yahoo.com  2020-07-13  44891.0        NaN
1483  kathleenbell@yahoo.com  2020-07-13  44891.0        NaN


Duplicate rows for ID 030bc551-1402-43cb-85dc-2f06ea968a4c:
                                        ID           Name   Age  \
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0

                           Email   Join Date   Salary Department
7402  gutierrezcrystal@gmail.com  1986-11-03  54228.0      Sales
7402  gutierrezcrystal@gmail.com  2023-02-01  54228.0      Sales


Duplicate rows for ID 0384957f-6bde-4234-a5b2-6e63be63170a:
                                        ID             Name   Age Email  \
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0  None
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0  None

       Join Date     Salary Department
7122  2020-08-18  145001.00      Sales
7122  1985-12-26  123249.83      Sales


Duplicate rows for ID 03aeb412-3c27-435f-a878-d86a76f0085e:
                                        ID              Name   Age Email  \
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0  None
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0  None

       Join Date     Salary   Department
9979  2020-07-26  108725.00  Engineering
9979  2020-07-26  126650.23  Engineering


Duplicate rows for ID 0413800c-975f-4107-908c-f9f733496b3c:
                                        ID         Name   Age Email Join Date  \
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0  None       NaN
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0  None       NaN

        Salary Department
8410  56011.00         HR
8410  58724.83         HR


Duplicate rows for ID 04ac7c93-4d85-400a-9cfe-b8155e26aa68:
                                        ID                 Name   Age  \
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jonesbuilding  85.0
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68          Megan Jones  85.0

                        Email   Join Date    Salary Department
7330  wrightmatthew@gmail.com  2021-08-18   90211.5      Sales
7330  wrightmatthew@gmail.com  2021-08-18  112474.0      Sales


Duplicate rows for ID 04cc2159-52ce-446c-bb83-10d4ec32b30a:
                                       ID                Name   Age  \
303  04cc2159-52ce-446c-bb83-10d4ec32b30a       Patrick Oneil  49.0
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneillseem  49.0

                          Email   Join Date     Salary Department
303  jeffreyhernandez@yahoo.com  2021-04-17  144887.00    Support
303  jeffreyhernandez@yahoo.com  2021-04-17  173539.45    Support


Duplicate rows for ID 058d4d45-bdb0-4864-b38c-578fde6e3ef3:
                                        ID             Name   Age  \
9980  058d4d45-bdb0-4864-b38c-578fde6e3ef3      Casey Smith  28.0
9980  058d4d45-bdb0-4864-b38c-578fde6e3ef3  Casey Smithlive  28.0

                  Email   Join Date   Salary   Department
9980  julie77@yahoo.com  2021-02-15  55617.0  Engineering
9980  julie77@yahoo.com  2021-02-15  55617.0  Engineering


Duplicate rows for ID 05c7d64e-0fec-44ee-88fe-eb3d3621e572:
                                        ID              Name   Age  \
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0

                       Email   Join Date     Salary Department
3866  delgadobobby@gmail.com  2020-04-29  121422.28    Support
3866  delgadobobby@gmail.com  2020-04-29  107416.00    Support


Duplicate rows for ID 07638d51-1811-433a-b883-63e93aeab3eb:
                                        ID            Name   Age  \
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0

                     Email   Join Date  Salary Department
9224  katiecombs@yahoo.com  1985-08-17     NaN    Support
9224  katiecombs@yahoo.com  2023-09-23     NaN    Support


Duplicate rows for ID 07ca0c58-b7b2-47a0-912e-f3ffb5eb6351:
                                        ID                 Name   Age  \
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351        Kevin Vincent  51.0
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincentreveal  51.0

                         Email   Join Date     Salary Department
9486  michellemosley@gmail.com  2022-11-09  153498.14  Marketing
9486  michellemosley@gmail.com  2022-11-09  145417.00  Marketing


Duplicate rows for ID 080400bb-3bcf-4880-bb24-dc3a23584b33:
                                        ID        Name   Age  \
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0

                        Email   Join Date   Salary Department
9309  melissawilson@yahoo.com  2022-10-28  62200.0        NaN
9309  melissawilson@yahoo.com  2022-05-14  62200.0        NaN


Duplicate rows for ID 081b1c6d-9dfe-473c-96a2-ec770fcdb61c:
                                        ID            Name   Age  \
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0

                     Email   Join Date   Salary Department
4861  jennifer35@yahoo.com  2020-07-21  81532.0        NaN
4861  jennifer35@yahoo.com  1970-11-12  81532.0        NaN


Duplicate rows for ID 0935d2f1-d2e0-4ce9-9978-a4f56bcd27f2:
                                        ID                Name   Age  \
6117  0935d2f1-d2e0-4ce9-9978-a4f56bcd27f2  Julia Myersproduct  71.0
6117  0935d2f1-d2e0-4ce9-9978-a4f56bcd27f2         Julia Myers  71.0

                          Email   Join Date  Salary Department
6117  bryantdarrell@hotmail.com  2022-04-28     NaN         HR
6117  bryantdarrell@hotmail.com  2022-04-28     NaN         HR


Duplicate rows for ID 09582335-b0bc-46b2-81a8-e7bf0439b4d0:
                                        ID                     Name   Age  \
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0            Kathleen Diaz  53.0
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diazthroughout  53.0

                        Email   Join Date    Salary Department
9842  nicholekelley@yahoo.com  1970-02-18  139179.0      Sales
9842  nicholekelley@yahoo.com  2001-09-12  139179.0      Sales


Duplicate rows for ID 0a556cb2-ed1c-42ea-8462-6b9b3e18ec16:
                                        ID  Name   Age                Email  \
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  None  47.0  breanna49@yahoo.com
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  None  47.0  breanna49@yahoo.com

       Join Date   Salary   Department
7162  1995-11-21  46931.0  Engineering
7162  2020-04-28  46931.0  Engineering


Duplicate rows for ID 0b7ea886-cc5b-418a-bd15-cc003d6c53b2:
                                        ID         Name   Age Email Join Date  \
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0  None       NaN
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0  None       NaN

        Salary Department
3115  96594.00      Sales
3115  77298.04      Sales


Duplicate rows for ID 0b99e355-53b5-42f0-985b-a7f25878f69a:
                                        ID                        Name   Age  \
5224  0b99e355-53b5-42f0-985b-a7f25878f69a               April Hawkins  39.0
5224  0b99e355-53b5-42f0-985b-a7f25878f69a  April Hawkinsinternational  39.0

     Email   Join Date   Salary Department
5224  None  2022-05-04  80508.0      Sales
5224  None  2022-05-04  80508.0      Sales


Duplicate rows for ID 0bf01dfc-44ca-444b-9123-47f08b1491cc:
                                        ID          Name   Age  \
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0

                        Email Join Date     Salary Department
3783  christopher54@gmail.com       NaN  132066.00    Support
3783  christopher54@gmail.com       NaN  133919.41    Support


Duplicate rows for ID 0c6f904d-4e2f-4a5e-bf22-5bcf361fddb2:
                                        ID                  Name   Age Email  \
9820  0c6f904d-4e2f-4a5e-bf22-5bcf361fddb2  Tammy Randolphbetter  59.0  None
9820  0c6f904d-4e2f-4a5e-bf22-5bcf361fddb2        Tammy Randolph  59.0  None

       Join Date    Salary   Department
9820  2022-08-27  103354.0  Engineering
9820  2022-08-27  103354.0  Engineering


Duplicate rows for ID 0c8b9d1d-6b72-4414-b062-fbf6775b2556:
                                       ID                Name   Age  \
374  0c8b9d1d-6b72-4414-b062-fbf6775b2556  Lisa Martinbrother  45.0
374  0c8b9d1d-6b72-4414-b062-fbf6775b2556         Lisa Martin  45.0

                   Email   Join Date    Salary   Department
374  monique76@yahoo.com  2021-10-27  114573.0  Engineering
374  monique76@yahoo.com  2021-10-27  114573.0  Engineering


Duplicate rows for ID 0c9f393a-9dae-4a85-9a2d-a11da100d90a:
                                        ID              Name   Age  \
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0

                    Email   Join Date   Salary Department
8302  cgaines@hotmail.com  2023-08-19  89861.0    Support
8302  cgaines@hotmail.com  1991-02-18  89861.0    Support


Duplicate rows for ID 0d1c4ccd-5b37-4082-889e-0f0a75861db2:
                                        ID                Name   Age Email  \
2895  0d1c4ccd-5b37-4082-889e-0f0a75861db2  Lisa Thompsoncolor  52.0  None
2895  0d1c4ccd-5b37-4082-889e-0f0a75861db2       Lisa Thompson  52.0  None

       Join Date   Salary Department
2895  2023-03-23  75756.0    Support
2895  2023-03-23  75756.0    Support


Duplicate rows for ID 0e8efa97-33ca-4b0d-b234-6d818dfe6008:
                                        ID         Name   Age Email  \
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0  None
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0  None

       Join Date    Salary Department
5711  2000-06-04  144565.0  Marketing
5711  2004-11-13  144565.0  Marketing


Duplicate rows for ID 0f1ac219-bdee-4e6d-87e8-2bce16aeae22:
                                        ID                Name  Age Email  \
9063  0f1ac219-bdee-4e6d-87e8-2bce16aeae22  Melinda Kanereveal  NaN  None
9063  0f1ac219-bdee-4e6d-87e8-2bce16aeae22        Melinda Kane  NaN  None

       Join Date   Salary Department
9063  2023-01-17  87351.0  Marketing
9063  2023-01-17  87351.0  Marketing


Duplicate rows for ID 0f6d137c-fd37-4689-b951-ac0c5efc26b5:
                                        ID                   Name   Age  \
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thorntonwhatever  67.0
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5          Gary Thornton  67.0

                        Email   Join Date   Salary Department
7235  tiffanycooper@yahoo.com  2020-01-13  85101.0    Support
7235  tiffanycooper@yahoo.com  1982-12-21  85101.0    Support


Duplicate rows for ID 0ff202a5-e9d9-42b1-8a1c-b46ec8575d99:
                                       ID                 Name   Age Email  \
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99       Jeffrey Medina  36.0  None
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medinapoint  36.0  None

      Join Date     Salary   Department
646  2022-06-01  145991.14  Engineering
646  2022-06-01  142446.00  Engineering


Duplicate rows for ID 10944e3d-1a81-4df5-8f75-b5ae1fc3e461:
                                        ID         Name   Age  \
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0

                      Email   Join Date     Salary   Department
8763  qwilliams@hotmail.com  2021-03-04  125692.59  Engineering
8763  qwilliams@hotmail.com  2021-03-04  133695.08  Engineering


Duplicate rows for ID 109a7c13-ebde-4749-8229-5b408d340a29:
                                        ID              Name   Age  \
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0

                        Email   Join Date   Salary Department
9721  karenphelps@hotmail.com  2023-04-14  94134.0        NaN
9721  karenphelps@hotmail.com  1981-02-13  94134.0        NaN


Duplicate rows for ID 10a30c02-789f-41c2-b184-e47108a71303:
                                        ID        Name   Age  \
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0

                           Email   Join Date    Salary Department
7848  turnerkimberly@hotmail.com  1971-12-30  35918.00      Sales
7848  turnerkimberly@hotmail.com  2022-10-06  42330.31      Sales


Duplicate rows for ID 10c26512-ce3a-4387-b71a-47768503562e:
                                        ID               Name   Age  \
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0

                Email   Join Date    Salary Department
3317  rmccoy@hall.com  2020-06-11  62967.69  Marketing
3317  rmccoy@hall.com  2020-06-11  60950.50  Marketing


Duplicate rows for ID 116e5e89-b6d1-4c0c-bf9e-a7db34d70188:
                                        ID                   Name   Age Email  \
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188        Taylor Morrison  78.0  None
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrisonassume  78.0  None

       Join Date    Salary Department
1574  2023-08-06  67498.14      Sales
1574  2023-08-06  62308.00      Sales


Duplicate rows for ID 1186cdff-ef30-453c-9b73-d586383a60ad:
                                        ID        Name   Age Email  \
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0  None
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0  None

       Join Date    Salary Department
9752  1973-10-15  145859.0  Marketing
9752  2021-06-02  145859.0  Marketing


Duplicate rows for ID 11a0a2ac-31d3-4dae-98fb-4e3f4d95da65:
                                       ID          Name   Age Email Join Date  \
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0  None       NaN
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0  None       NaN

        Salary Department
472  103412.01      Sales
472  101631.00      Sales


Duplicate rows for ID 126d1500-9869-44ae-92c4-c818a2b57d93:
                                        ID          Name   Age Email  \
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0  None
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0  None

       Join Date    Salary Department
6732  2021-06-08  113129.0         HR
6732  1976-09-03  113129.0         HR


Duplicate rows for ID 12a7c52d-bb72-409f-b3d7-4232aa3f0a34:
                                        ID                    Name   Age  \
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Robertsvisit  35.0
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34       Christine Roberts  35.0

                     Email   Join Date     Salary Department
7249  claireross@gmail.com  2022-04-07  109754.14    Support
7249  claireross@gmail.com  2022-04-07   94493.00    Support


Duplicate rows for ID 12dde7ca-6754-4a28-81c1-ff8adaf39365:
                                        ID           Name   Age Email  \
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0  None
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0  None

       Join Date    Salary Department
7652  1975-08-09  87262.43         HR
7652  2022-09-16  76189.81         HR


Duplicate rows for ID 1351ae68-3605-48fd-8cc2-e88d9d990d1d:
                                        ID         Name   Age Email  \
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0  None
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0  None

       Join Date   Salary Department
4945  2020-03-12  63094.0    Support
4945  2004-02-07  63094.0    Support


Duplicate rows for ID 135232d5-4e2e-46d5-82b4-47a622b911f5:
                                        ID                Name   Age  \
9049  135232d5-4e2e-46d5-82b4-47a622b911f5     Timothy Kennedy  78.0
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedyboy  78.0

                    Email   Join Date   Salary Department
9049  tyler40@hotmail.com  1978-02-26  46881.0    Support
9049  tyler40@hotmail.com  2022-01-29  46881.0    Support


Duplicate rows for ID 13552825-66be-49cd-85bc-f1d117290c9f:
                                        ID  Name   Age Email   Join Date  \
6835  13552825-66be-49cd-85bc-f1d117290c9f  None  57.0  None  2021-08-26
6835  13552825-66be-49cd-85bc-f1d117290c9f  None  57.0  None  2021-08-26

        Salary Department
6835  75630.35  Marketing
6835  79636.00  Marketing


Duplicate rows for ID 13a4ee07-a58a-4a2b-a249-8cec5e256e58:
                                        ID             Name   Age  \
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0

                         Email   Join Date   Salary Department
7276  delgadojeffrey@yahoo.com  2022-06-08  62183.0         HR
7276  delgadojeffrey@yahoo.com  2022-03-16  62183.0         HR


Duplicate rows for ID 14452655-08d2-4698-8498-74f30a5e9f9f:

In [35]:
# checking the combination of ID and Name to fill null values with valid names if both entries have same ID.
data["Name"] = data.groupby("ID")["Name"].transform(lambda x: x.fillna(method="ffill").fillna(method="bfill"))

data["Name"] = data["Name"].fillna("Unknown")
def get_shortest_name(group):
    valid_names = group.dropna().unique()  # Get unique non-NaN values
    if len(valid_names) == 0:
        return "Unknown"  # If no valid names exist, return default
    return min(valid_names, key=len)  # Select shortest name safely

# Step 4: Compute shortest name per ID group
shortest_names = data.groupby("ID")["Name"].apply(get_shortest_name)

# Step 5: Assign the shortest name back to the dataset
data["Name"] = data["ID"].map(shortest_names)

In [36]:
data.shape

(9480, 7)

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9480 entries, 0 to 7648
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          9480 non-null   object
 1   Name        9480 non-null   object
 2   Age         9012 non-null   float64
 3   Email       4567 non-null   object
 4   Join Date   8592 non-null   object
 5   Salary      8542 non-null   float64
 6   Department  8516 non-null   object
dtypes: float64(2), object(5)
memory usage: 592.5+ KB

In [38]:
duplicate_value()

Duplicate rows for ID 0053781e-61aa-423e-ae39-adc1ee24f24c:
                                        ID           Name   Age Email  \
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0  None
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0  None

       Join Date    Salary Department
1009  2020-02-23  140100.0  Marketing
1009  2022-01-02  140100.0  Marketing


Duplicate rows for ID 00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e:
                                        ID          Name   Age Email  \
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0  None
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0  None

       Join Date   Salary Department
7942  1991-08-13  63500.0  Marketing
7942  2020-03-17  63500.0  Marketing


Duplicate rows for ID 00d23202-87b8-49bf-bec4-deea25ca43f4:
                                        ID                  Name   Age Email  \
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0  None
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0  None

     Join Date    Salary Department
9851       NaN  36948.17         HR
9851       NaN  44371.00         HR


Duplicate rows for ID 019f2dce-1c6b-48a3-975a-b5fc0f524662:
                                        ID                Name   Age Email  \
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0  None
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0  None

       Join Date     Salary Department
6302  2020-06-20  108294.68  Marketing
6302  2020-06-20  110313.00  Marketing


Duplicate rows for ID 02d6256d-a177-46b6-aaf8-6e18063336e5:
                                       ID     Name   Age                Email  \
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com

      Join Date    Salary Department
939  2023-08-16  140138.0         HR
939  2006-07-10  140138.0         HR


Duplicate rows for ID 02db9c6e-d4fc-4321-9556-11b01bb12bb9:
                                       ID            Name   Age Email  \
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0  None
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0  None

      Join Date  Salary Department
587  1989-01-08     NaN    Support
587  1970-06-19     NaN    Support


Duplicate rows for ID 02fae873-2e0a-4e1d-94d3-3de1d6476f31:
                                        ID        Name   Age  \
1483  02fae873-2e0a-4e1d-94d3-3de1d6476f31  Mike Woods  31.0
1483  02fae873-2e0a-4e1d-94d3-3de1d6476f31  Mike Woods  31.0

                       Email   Join Date   Salary Department
1483  kathleenbell@yahoo.com  2020-07-13  44891.0        NaN
1483  kathleenbell@yahoo.com  2020-07-13  44891.0        NaN


Duplicate rows for ID 030bc551-1402-43cb-85dc-2f06ea968a4c:
                                        ID           Name   Age  \
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0

                           Email   Join Date   Salary Department
7402  gutierrezcrystal@gmail.com  1986-11-03  54228.0      Sales
7402  gutierrezcrystal@gmail.com  2023-02-01  54228.0      Sales


Duplicate rows for ID 0384957f-6bde-4234-a5b2-6e63be63170a:
                                        ID             Name   Age Email  \
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0  None
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0  None

       Join Date     Salary Department
7122  2020-08-18  145001.00      Sales
7122  1985-12-26  123249.83      Sales


Duplicate rows for ID 03aeb412-3c27-435f-a878-d86a76f0085e:
                                        ID              Name   Age Email  \
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0  None
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0  None

       Join Date     Salary   Department
9979  2020-07-26  108725.00  Engineering
9979  2020-07-26  126650.23  Engineering


Duplicate rows for ID 0413800c-975f-4107-908c-f9f733496b3c:
                                        ID         Name   Age Email Join Date  \
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0  None       NaN
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0  None       NaN

        Salary Department
8410  56011.00         HR
8410  58724.83         HR


Duplicate rows for ID 04ac7c93-4d85-400a-9cfe-b8155e26aa68:
                                        ID         Name   Age  \
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0

                        Email   Join Date    Salary Department
7330  wrightmatthew@gmail.com  2021-08-18   90211.5      Sales
7330  wrightmatthew@gmail.com  2021-08-18  112474.0      Sales


Duplicate rows for ID 04cc2159-52ce-446c-bb83-10d4ec32b30a:
                                       ID           Name   Age  \
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0

                          Email   Join Date     Salary Department
303  jeffreyhernandez@yahoo.com  2021-04-17  144887.00    Support
303  jeffreyhernandez@yahoo.com  2021-04-17  173539.45    Support


Duplicate rows for ID 058d4d45-bdb0-4864-b38c-578fde6e3ef3:
                                        ID         Name   Age  \
9980  058d4d45-bdb0-4864-b38c-578fde6e3ef3  Casey Smith  28.0
9980  058d4d45-bdb0-4864-b38c-578fde6e3ef3  Casey Smith  28.0

                  Email   Join Date   Salary   Department
9980  julie77@yahoo.com  2021-02-15  55617.0  Engineering
9980  julie77@yahoo.com  2021-02-15  55617.0  Engineering


Duplicate rows for ID 05c7d64e-0fec-44ee-88fe-eb3d3621e572:
                                        ID              Name   Age  \
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0

                       Email   Join Date     Salary Department
3866  delgadobobby@gmail.com  2020-04-29  121422.28    Support
3866  delgadobobby@gmail.com  2020-04-29  107416.00    Support


Duplicate rows for ID 07638d51-1811-433a-b883-63e93aeab3eb:
                                        ID            Name   Age  \
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0

                     Email   Join Date  Salary Department
9224  katiecombs@yahoo.com  1985-08-17     NaN    Support
9224  katiecombs@yahoo.com  2023-09-23     NaN    Support


Duplicate rows for ID 07ca0c58-b7b2-47a0-912e-f3ffb5eb6351:
                                        ID           Name   Age  \
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0

                         Email   Join Date     Salary Department
9486  michellemosley@gmail.com  2022-11-09  153498.14  Marketing
9486  michellemosley@gmail.com  2022-11-09  145417.00  Marketing


Duplicate rows for ID 080400bb-3bcf-4880-bb24-dc3a23584b33:
                                        ID        Name   Age  \
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0

                        Email   Join Date   Salary Department
9309  melissawilson@yahoo.com  2022-10-28  62200.0        NaN
9309  melissawilson@yahoo.com  2022-05-14  62200.0        NaN


Duplicate rows for ID 081b1c6d-9dfe-473c-96a2-ec770fcdb61c:
                                        ID            Name   Age  \
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0

                     Email   Join Date   Salary Department
4861  jennifer35@yahoo.com  2020-07-21  81532.0        NaN
4861  jennifer35@yahoo.com  1970-11-12  81532.0        NaN


Duplicate rows for ID 0935d2f1-d2e0-4ce9-9978-a4f56bcd27f2:
                                        ID         Name   Age  \
6117  0935d2f1-d2e0-4ce9-9978-a4f56bcd27f2  Julia Myers  71.0
6117  0935d2f1-d2e0-4ce9-9978-a4f56bcd27f2  Julia Myers  71.0

                          Email   Join Date  Salary Department
6117  bryantdarrell@hotmail.com  2022-04-28     NaN         HR
6117  bryantdarrell@hotmail.com  2022-04-28     NaN         HR


Duplicate rows for ID 09582335-b0bc-46b2-81a8-e7bf0439b4d0:
                                        ID           Name   Age  \
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0

                        Email   Join Date    Salary Department
9842  nicholekelley@yahoo.com  1970-02-18  139179.0      Sales
9842  nicholekelley@yahoo.com  2001-09-12  139179.0      Sales


Duplicate rows for ID 0a556cb2-ed1c-42ea-8462-6b9b3e18ec16:
                                        ID     Name   Age  \
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0

                    Email   Join Date   Salary   Department
7162  breanna49@yahoo.com  1995-11-21  46931.0  Engineering
7162  breanna49@yahoo.com  2020-04-28  46931.0  Engineering


Duplicate rows for ID 0b7ea886-cc5b-418a-bd15-cc003d6c53b2:
                                        ID         Name   Age Email Join Date  \
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0  None       NaN
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0  None       NaN

        Salary Department
3115  96594.00      Sales
3115  77298.04      Sales


Duplicate rows for ID 0b99e355-53b5-42f0-985b-a7f25878f69a:
                                        ID           Name   Age Email  \
5224  0b99e355-53b5-42f0-985b-a7f25878f69a  April Hawkins  39.0  None
5224  0b99e355-53b5-42f0-985b-a7f25878f69a  April Hawkins  39.0  None

       Join Date   Salary Department
5224  2022-05-04  80508.0      Sales
5224  2022-05-04  80508.0      Sales


Duplicate rows for ID 0bf01dfc-44ca-444b-9123-47f08b1491cc:
                                        ID          Name   Age  \
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0

                        Email Join Date     Salary Department
3783  christopher54@gmail.com       NaN  132066.00    Support
3783  christopher54@gmail.com       NaN  133919.41    Support


Duplicate rows for ID 0c6f904d-4e2f-4a5e-bf22-5bcf361fddb2:
                                        ID            Name   Age Email  \
9820  0c6f904d-4e2f-4a5e-bf22-5bcf361fddb2  Tammy Randolph  59.0  None
9820  0c6f904d-4e2f-4a5e-bf22-5bcf361fddb2  Tammy Randolph  59.0  None

       Join Date    Salary   Department
9820  2022-08-27  103354.0  Engineering
9820  2022-08-27  103354.0  Engineering


Duplicate rows for ID 0c8b9d1d-6b72-4414-b062-fbf6775b2556:
                                       ID         Name   Age  \
374  0c8b9d1d-6b72-4414-b062-fbf6775b2556  Lisa Martin  45.0
374  0c8b9d1d-6b72-4414-b062-fbf6775b2556  Lisa Martin  45.0

                   Email   Join Date    Salary   Department
374  monique76@yahoo.com  2021-10-27  114573.0  Engineering
374  monique76@yahoo.com  2021-10-27  114573.0  Engineering


Duplicate rows for ID 0c9f393a-9dae-4a85-9a2d-a11da100d90a:
                                        ID              Name   Age  \
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0

                    Email   Join Date   Salary Department
8302  cgaines@hotmail.com  2023-08-19  89861.0    Support
8302  cgaines@hotmail.com  1991-02-18  89861.0    Support


Duplicate rows for ID 0d1c4ccd-5b37-4082-889e-0f0a75861db2:
                                        ID           Name   Age Email  \
2895  0d1c4ccd-5b37-4082-889e-0f0a75861db2  Lisa Thompson  52.0  None
2895  0d1c4ccd-5b37-4082-889e-0f0a75861db2  Lisa Thompson  52.0  None

       Join Date   Salary Department
2895  2023-03-23  75756.0    Support
2895  2023-03-23  75756.0    Support


Duplicate rows for ID 0e8efa97-33ca-4b0d-b234-6d818dfe6008:
                                        ID         Name   Age Email  \
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0  None
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0  None

       Join Date    Salary Department
5711  2000-06-04  144565.0  Marketing
5711  2004-11-13  144565.0  Marketing


Duplicate rows for ID 0f1ac219-bdee-4e6d-87e8-2bce16aeae22:
                                        ID          Name  Age Email  \
9063  0f1ac219-bdee-4e6d-87e8-2bce16aeae22  Melinda Kane  NaN  None
9063  0f1ac219-bdee-4e6d-87e8-2bce16aeae22  Melinda Kane  NaN  None

       Join Date   Salary Department
9063  2023-01-17  87351.0  Marketing
9063  2023-01-17  87351.0  Marketing


Duplicate rows for ID 0f6d137c-fd37-4689-b951-ac0c5efc26b5:
                                        ID           Name   Age  \
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0

                        Email   Join Date   Salary Department
7235  tiffanycooper@yahoo.com  2020-01-13  85101.0    Support
7235  tiffanycooper@yahoo.com  1982-12-21  85101.0    Support


Duplicate rows for ID 0ff202a5-e9d9-42b1-8a1c-b46ec8575d99:
                                       ID            Name   Age Email  \
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0  None
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0  None

      Join Date     Salary   Department
646  2022-06-01  145991.14  Engineering
646  2022-06-01  142446.00  Engineering


Duplicate rows for ID 10944e3d-1a81-4df5-8f75-b5ae1fc3e461:
                                        ID         Name   Age  \
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0

                      Email   Join Date     Salary   Department
8763  qwilliams@hotmail.com  2021-03-04  125692.59  Engineering
8763  qwilliams@hotmail.com  2021-03-04  133695.08  Engineering


Duplicate rows for ID 109a7c13-ebde-4749-8229-5b408d340a29:
                                        ID              Name   Age  \
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0

                        Email   Join Date   Salary Department
9721  karenphelps@hotmail.com  2023-04-14  94134.0        NaN
9721  karenphelps@hotmail.com  1981-02-13  94134.0        NaN


Duplicate rows for ID 10a30c02-789f-41c2-b184-e47108a71303:
                                        ID        Name   Age  \
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0

                           Email   Join Date    Salary Department
7848  turnerkimberly@hotmail.com  1971-12-30  35918.00      Sales
7848  turnerkimberly@hotmail.com  2022-10-06  42330.31      Sales


Duplicate rows for ID 10c26512-ce3a-4387-b71a-47768503562e:
                                        ID               Name   Age  \
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0

                Email   Join Date    Salary Department
3317  rmccoy@hall.com  2020-06-11  62967.69  Marketing
3317  rmccoy@hall.com  2020-06-11  60950.50  Marketing


Duplicate rows for ID 116e5e89-b6d1-4c0c-bf9e-a7db34d70188:
                                        ID             Name   Age Email  \
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0  None
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0  None

       Join Date    Salary Department
1574  2023-08-06  67498.14      Sales
1574  2023-08-06  62308.00      Sales


Duplicate rows for ID 1186cdff-ef30-453c-9b73-d586383a60ad:
                                        ID        Name   Age Email  \
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0  None
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0  None

       Join Date    Salary Department
9752  1973-10-15  145859.0  Marketing
9752  2021-06-02  145859.0  Marketing


Duplicate rows for ID 11a0a2ac-31d3-4dae-98fb-4e3f4d95da65:
                                       ID          Name   Age Email Join Date  \
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0  None       NaN
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0  None       NaN

        Salary Department
472  103412.01      Sales
472  101631.00      Sales


Duplicate rows for ID 126d1500-9869-44ae-92c4-c818a2b57d93:
                                        ID          Name   Age Email  \
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0  None
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0  None

       Join Date    Salary Department
6732  2021-06-08  113129.0         HR
6732  1976-09-03  113129.0         HR


Duplicate rows for ID 12a7c52d-bb72-409f-b3d7-4232aa3f0a34:
                                        ID               Name   Age  \
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0

                     Email   Join Date     Salary Department
7249  claireross@gmail.com  2022-04-07  109754.14    Support
7249  claireross@gmail.com  2022-04-07   94493.00    Support


Duplicate rows for ID 12dde7ca-6754-4a28-81c1-ff8adaf39365:
                                        ID           Name   Age Email  \
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0  None
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0  None

       Join Date    Salary Department
7652  1975-08-09  87262.43         HR
7652  2022-09-16  76189.81         HR


Duplicate rows for ID 1351ae68-3605-48fd-8cc2-e88d9d990d1d:
                                        ID         Name   Age Email  \
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0  None
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0  None

       Join Date   Salary Department
4945  2020-03-12  63094.0    Support
4945  2004-02-07  63094.0    Support


Duplicate rows for ID 135232d5-4e2e-46d5-82b4-47a622b911f5:
                                        ID             Name   Age  \
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0

                    Email   Join Date   Salary Department
9049  tyler40@hotmail.com  1978-02-26  46881.0    Support
9049  tyler40@hotmail.com  2022-01-29  46881.0    Support


Duplicate rows for ID 13552825-66be-49cd-85bc-f1d117290c9f:
                                        ID     Name   Age Email   Join Date  \
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  None  2021-08-26
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  None  2021-08-26

        Salary Department
6835  75630.35  Marketing
6835  79636.00  Marketing


Duplicate rows for ID 13a4ee07-a58a-4a2b-a249-8cec5e256e58:
                                        ID             Name   Age  \
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0

                         Email   Join Date   Salary Department
7276  delgadojeffrey@yahoo.com  2022-06-08  62183.0         HR
7276  delgadojeffrey@yahoo.com  2022-03-16  62183.0         HR


Duplicate rows for ID 14452655-08d2-4698-8498-74f30a5e9f9f:
                                        ID     Name   Age Email   Join Date  \
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  None  1979-06-19
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  None  2021-02-26

         Salary Department
1877  144339.00    Support
1877  144311.66    Support



In [39]:
data.head(10)

,ID,Name,Age,Email,Join Date,Salary,Department
0,1e407ff9-6255-489d-a0de-34135d4f74bd,Hunter Thomas,25.0,xlopez@hotmail.com,NaN,88552.00,Sales
1,379f55b8-87d5-4739-a146-7400b78c24d1,Jeremy Irwin,90.0,None,2022-07-07,139227.00,NaN
2,18261368-dfa1-47f0-afc6-bddf45926b07,Jennifer Hammondquickly,66.0,None,2023-11-21,65550.00,Engineering
3,ae7cf7cf-17cf-4c8b-9c44-4f61a9a238e5,Sydney Taylorso,39.0,None,2021-11-05,139932.00,Support
4,14ed3e6a-e0f5-4bbe-8d93-8665267f5c90,Julia Le,71.0,figueroakayla@yahoo.com,NaN,143456.00,Marketing
5,f92ea13f-24d3-4792-91e4-5b0e07d90c2c,Lisa Bailey,81.0,None,2016-10-15,123018.00,Support
6,c4892dbb-2554-4ce1-8f11-f6597d7f6782,Patricia Brown,66.0,pperkins@hotmail.com,2020-09-17,77311.00,HR
7,465e625b-f924-4061-8356-c7e3130f7118,Derek Murphy,38.0,josephrobertson@gmail.com,2021-01-12,NaN,Support
8,12cc2f16-d641-402e-b22b-3332bafc4f1d,Unknown,71.0,andrew74@hotmail.com,2022-02-12,83354.00,Sales
9,d06f507d-62e5-4bd6-a252-4e60e109d324,Jay Fisher,44.0,None,2022-12-08,37701.73,HR

In [40]:
data.tail(10)

,ID,Name,Age,Email,Join Date,Salary,Department
5299,f82d65c8-f4bb-485f-8dc5-2e454fda6fad,Curtis Moses,46.0,None,2022-11-21,36596.00,Marketing
1558,a09fc4c8-eca3-4eec-bd4c-64540dcd2f7e,Madison Mclaughlin,74.0,None,2024-03-24,50557.05,Marketing
3783,0bf01dfc-44ca-444b-9123-47f08b1491cc,Joseph Jones,43.0,christopher54@gmail.com,NaN,133919.41,Support
5620,4d450808-7caf-432e-bf65-385e715b43fe,Richard Leonard,58.0,luis19@gmail.com,1982-01-05,103005.00,HR
3317,10c26512-ce3a-4387-b71a-47768503562e,Kimberly Cummings,54.0,rmccoy@hall.com,2020-06-11,60950.50,Marketing
9603,612011e6-101d-4ee2-bbca-16a5056d8217,Jeffrey Elliottnation,72.0,None,2021-08-05,50510.78,Support
9510,796f8c0b-15a4-475c-bb02-ac892df0c746,Shelley Hopkins,79.0,None,1992-12-25,47809.00,HR
9785,da8a6bbc-5026-4630-848d-f64e80dac56c,Steven Armstrong,38.0,molly89@gmail.com,2021-06-24,NaN,Sales
7826,ed19c966-d6d8-4047-b410-b6e595a39340,Stephanie Rios,NaN,None,2006-08-15,122609.59,HR
7648,783b36b4-d09f-46c9-8a52-7ff96b80863e,Bonnie Benitez,37.0,None,2020-10-09,147322.01,Support

In [41]:
data=data.drop_duplicates()

In [42]:
data.shape

(9355, 7)

In [43]:
duplicate_value()

Duplicate rows for ID 0053781e-61aa-423e-ae39-adc1ee24f24c:
                                        ID           Name   Age Email  \
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0  None
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0  None

       Join Date    Salary Department
1009  2020-02-23  140100.0  Marketing
1009  2022-01-02  140100.0  Marketing


Duplicate rows for ID 00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e:
                                        ID          Name   Age Email  \
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0  None
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0  None

       Join Date   Salary Department
7942  1991-08-13  63500.0  Marketing
7942  2020-03-17  63500.0  Marketing


Duplicate rows for ID 00d23202-87b8-49bf-bec4-deea25ca43f4:
                                        ID                  Name   Age Email  \
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0  None
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0  None

     Join Date    Salary Department
9851       NaN  36948.17         HR
9851       NaN  44371.00         HR


Duplicate rows for ID 019f2dce-1c6b-48a3-975a-b5fc0f524662:
                                        ID                Name   Age Email  \
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0  None
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0  None

       Join Date     Salary Department
6302  2020-06-20  108294.68  Marketing
6302  2020-06-20  110313.00  Marketing


Duplicate rows for ID 02d6256d-a177-46b6-aaf8-6e18063336e5:
                                       ID     Name   Age                Email  \
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com

      Join Date    Salary Department
939  2023-08-16  140138.0         HR
939  2006-07-10  140138.0         HR


Duplicate rows for ID 02db9c6e-d4fc-4321-9556-11b01bb12bb9:
                                       ID            Name   Age Email  \
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0  None
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0  None

      Join Date  Salary Department
587  1989-01-08     NaN    Support
587  1970-06-19     NaN    Support


Duplicate rows for ID 030bc551-1402-43cb-85dc-2f06ea968a4c:
                                        ID           Name   Age  \
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0

                           Email   Join Date   Salary Department
7402  gutierrezcrystal@gmail.com  1986-11-03  54228.0      Sales
7402  gutierrezcrystal@gmail.com  2023-02-01  54228.0      Sales


Duplicate rows for ID 0384957f-6bde-4234-a5b2-6e63be63170a:
                                        ID             Name   Age Email  \
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0  None
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0  None

       Join Date     Salary Department
7122  2020-08-18  145001.00      Sales
7122  1985-12-26  123249.83      Sales


Duplicate rows for ID 03aeb412-3c27-435f-a878-d86a76f0085e:
                                        ID              Name   Age Email  \
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0  None
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0  None

       Join Date     Salary   Department
9979  2020-07-26  108725.00  Engineering
9979  2020-07-26  126650.23  Engineering


Duplicate rows for ID 0413800c-975f-4107-908c-f9f733496b3c:
                                        ID         Name   Age Email Join Date  \
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0  None       NaN
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0  None       NaN

        Salary Department
8410  56011.00         HR
8410  58724.83         HR


Duplicate rows for ID 04ac7c93-4d85-400a-9cfe-b8155e26aa68:
                                        ID         Name   Age  \
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0

                        Email   Join Date    Salary Department
7330  wrightmatthew@gmail.com  2021-08-18   90211.5      Sales
7330  wrightmatthew@gmail.com  2021-08-18  112474.0      Sales


Duplicate rows for ID 04cc2159-52ce-446c-bb83-10d4ec32b30a:
                                       ID           Name   Age  \
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0

                          Email   Join Date     Salary Department
303  jeffreyhernandez@yahoo.com  2021-04-17  144887.00    Support
303  jeffreyhernandez@yahoo.com  2021-04-17  173539.45    Support


Duplicate rows for ID 05c7d64e-0fec-44ee-88fe-eb3d3621e572:
                                        ID              Name   Age  \
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0

                       Email   Join Date     Salary Department
3866  delgadobobby@gmail.com  2020-04-29  121422.28    Support
3866  delgadobobby@gmail.com  2020-04-29  107416.00    Support


Duplicate rows for ID 07638d51-1811-433a-b883-63e93aeab3eb:
                                        ID            Name   Age  \
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0

                     Email   Join Date  Salary Department
9224  katiecombs@yahoo.com  1985-08-17     NaN    Support
9224  katiecombs@yahoo.com  2023-09-23     NaN    Support


Duplicate rows for ID 07ca0c58-b7b2-47a0-912e-f3ffb5eb6351:
                                        ID           Name   Age  \
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0

                         Email   Join Date     Salary Department
9486  michellemosley@gmail.com  2022-11-09  153498.14  Marketing
9486  michellemosley@gmail.com  2022-11-09  145417.00  Marketing


Duplicate rows for ID 080400bb-3bcf-4880-bb24-dc3a23584b33:
                                        ID        Name   Age  \
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0

                        Email   Join Date   Salary Department
9309  melissawilson@yahoo.com  2022-10-28  62200.0        NaN
9309  melissawilson@yahoo.com  2022-05-14  62200.0        NaN


Duplicate rows for ID 081b1c6d-9dfe-473c-96a2-ec770fcdb61c:
                                        ID            Name   Age  \
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0

                     Email   Join Date   Salary Department
4861  jennifer35@yahoo.com  2020-07-21  81532.0        NaN
4861  jennifer35@yahoo.com  1970-11-12  81532.0        NaN


Duplicate rows for ID 09582335-b0bc-46b2-81a8-e7bf0439b4d0:
                                        ID           Name   Age  \
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0

                        Email   Join Date    Salary Department
9842  nicholekelley@yahoo.com  1970-02-18  139179.0      Sales
9842  nicholekelley@yahoo.com  2001-09-12  139179.0      Sales


Duplicate rows for ID 0a556cb2-ed1c-42ea-8462-6b9b3e18ec16:
                                        ID     Name   Age  \
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0

                    Email   Join Date   Salary   Department
7162  breanna49@yahoo.com  1995-11-21  46931.0  Engineering
7162  breanna49@yahoo.com  2020-04-28  46931.0  Engineering


Duplicate rows for ID 0b7ea886-cc5b-418a-bd15-cc003d6c53b2:
                                        ID         Name   Age Email Join Date  \
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0  None       NaN
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0  None       NaN

        Salary Department
3115  96594.00      Sales
3115  77298.04      Sales


Duplicate rows for ID 0bf01dfc-44ca-444b-9123-47f08b1491cc:
                                        ID          Name   Age  \
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0

                        Email Join Date     Salary Department
3783  christopher54@gmail.com       NaN  132066.00    Support
3783  christopher54@gmail.com       NaN  133919.41    Support


Duplicate rows for ID 0c9f393a-9dae-4a85-9a2d-a11da100d90a:
                                        ID              Name   Age  \
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0

                    Email   Join Date   Salary Department
8302  cgaines@hotmail.com  2023-08-19  89861.0    Support
8302  cgaines@hotmail.com  1991-02-18  89861.0    Support


Duplicate rows for ID 0e8efa97-33ca-4b0d-b234-6d818dfe6008:
                                        ID         Name   Age Email  \
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0  None
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0  None

       Join Date    Salary Department
5711  2000-06-04  144565.0  Marketing
5711  2004-11-13  144565.0  Marketing


Duplicate rows for ID 0f6d137c-fd37-4689-b951-ac0c5efc26b5:
                                        ID           Name   Age  \
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0

                        Email   Join Date   Salary Department
7235  tiffanycooper@yahoo.com  2020-01-13  85101.0    Support
7235  tiffanycooper@yahoo.com  1982-12-21  85101.0    Support


Duplicate rows for ID 0ff202a5-e9d9-42b1-8a1c-b46ec8575d99:
                                       ID            Name   Age Email  \
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0  None
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0  None

      Join Date     Salary   Department
646  2022-06-01  145991.14  Engineering
646  2022-06-01  142446.00  Engineering


Duplicate rows for ID 10944e3d-1a81-4df5-8f75-b5ae1fc3e461:
                                        ID         Name   Age  \
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0

                      Email   Join Date     Salary   Department
8763  qwilliams@hotmail.com  2021-03-04  125692.59  Engineering
8763  qwilliams@hotmail.com  2021-03-04  133695.08  Engineering


Duplicate rows for ID 109a7c13-ebde-4749-8229-5b408d340a29:
                                        ID              Name   Age  \
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0

                        Email   Join Date   Salary Department
9721  karenphelps@hotmail.com  2023-04-14  94134.0        NaN
9721  karenphelps@hotmail.com  1981-02-13  94134.0        NaN


Duplicate rows for ID 10a30c02-789f-41c2-b184-e47108a71303:
                                        ID        Name   Age  \
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0

                           Email   Join Date    Salary Department
7848  turnerkimberly@hotmail.com  1971-12-30  35918.00      Sales
7848  turnerkimberly@hotmail.com  2022-10-06  42330.31      Sales


Duplicate rows for ID 10c26512-ce3a-4387-b71a-47768503562e:
                                        ID               Name   Age  \
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0

                Email   Join Date    Salary Department
3317  rmccoy@hall.com  2020-06-11  62967.69  Marketing
3317  rmccoy@hall.com  2020-06-11  60950.50  Marketing


Duplicate rows for ID 116e5e89-b6d1-4c0c-bf9e-a7db34d70188:
                                        ID             Name   Age Email  \
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0  None
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0  None

       Join Date    Salary Department
1574  2023-08-06  67498.14      Sales
1574  2023-08-06  62308.00      Sales


Duplicate rows for ID 1186cdff-ef30-453c-9b73-d586383a60ad:
                                        ID        Name   Age Email  \
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0  None
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0  None

       Join Date    Salary Department
9752  1973-10-15  145859.0  Marketing
9752  2021-06-02  145859.0  Marketing


Duplicate rows for ID 11a0a2ac-31d3-4dae-98fb-4e3f4d95da65:
                                       ID          Name   Age Email Join Date  \
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0  None       NaN
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0  None       NaN

        Salary Department
472  103412.01      Sales
472  101631.00      Sales


Duplicate rows for ID 126d1500-9869-44ae-92c4-c818a2b57d93:
                                        ID          Name   Age Email  \
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0  None
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0  None

       Join Date    Salary Department
6732  2021-06-08  113129.0         HR
6732  1976-09-03  113129.0         HR


Duplicate rows for ID 12a7c52d-bb72-409f-b3d7-4232aa3f0a34:
                                        ID               Name   Age  \
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0

                     Email   Join Date     Salary Department
7249  claireross@gmail.com  2022-04-07  109754.14    Support
7249  claireross@gmail.com  2022-04-07   94493.00    Support


Duplicate rows for ID 12dde7ca-6754-4a28-81c1-ff8adaf39365:
                                        ID           Name   Age Email  \
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0  None
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0  None

       Join Date    Salary Department
7652  1975-08-09  87262.43         HR
7652  2022-09-16  76189.81         HR


Duplicate rows for ID 1351ae68-3605-48fd-8cc2-e88d9d990d1d:
                                        ID         Name   Age Email  \
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0  None
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0  None

       Join Date   Salary Department
4945  2020-03-12  63094.0    Support
4945  2004-02-07  63094.0    Support


Duplicate rows for ID 135232d5-4e2e-46d5-82b4-47a622b911f5:
                                        ID             Name   Age  \
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0

                    Email   Join Date   Salary Department
9049  tyler40@hotmail.com  1978-02-26  46881.0    Support
9049  tyler40@hotmail.com  2022-01-29  46881.0    Support


Duplicate rows for ID 13552825-66be-49cd-85bc-f1d117290c9f:
                                        ID     Name   Age Email   Join Date  \
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  None  2021-08-26
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  None  2021-08-26

        Salary Department
6835  75630.35  Marketing
6835  79636.00  Marketing


Duplicate rows for ID 13a4ee07-a58a-4a2b-a249-8cec5e256e58:
                                        ID             Name   Age  \
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0

                         Email   Join Date   Salary Department
7276  delgadojeffrey@yahoo.com  2022-06-08  62183.0         HR
7276  delgadojeffrey@yahoo.com  2022-03-16  62183.0         HR


Duplicate rows for ID 14452655-08d2-4698-8498-74f30a5e9f9f:
                                        ID     Name   Age Email   Join Date  \
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  None  1979-06-19
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  None  2021-02-26

         Salary Department
1877  144339.00    Support
1877  144311.66    Support


Duplicate rows for ID 144c46e8-f964-4374-96aa-ead07b754888:
                                        ID              Name   Age  \
3505  144c46e8-f964-4374-96aa-ead07b754888  Brandon Gonzalez  83.0
3505  144c46e8-f964-4374-96aa-ead07b754888  Brandon Gonzalez  83.0

                 Email Join Date    Salary Department
3505  dawn30@gmail.com       NaN  60280.00         HR
3505  dawn30@gmail.com       NaN  51886.35         HR


Duplicate rows for ID 153493fc-efe1-4530-8b3d-7f2c2518796b:
                                        ID          Name   Age Email  \
9214  153493fc-efe1-4530-8b3d-7f2c2518796b  Megan Nguyen  83.0  None
9214  153493fc-efe1-4530-8b3d-7f2c2518796b  Megan Nguyen  83.0  None

       Join Date    Salary   Department
9214  2020-02-18  92976.04  Engineering
9214  2020-02-18  80220.00  Engineering


Duplicate rows for ID 15352b0d-8c4e-4f4d-a16b-9f94e62fe7af:
                                       ID       Name   Age  \
623  15352b0d-8c4e-4f4d-a16b-9f94e62fe7af  Amy Clark  48.0
623  15352b0d-8c4e-4f4d-a16b-9f94e62fe7af  Amy Clark  48.0

                    Email   Join Date  Salary   Department
623  jonessusan@gmail.com  2017-07-11     NaN  Engineering
623  jonessusan@gmail.com  2023-04-23     NaN  Engineering


Duplicate rows for ID 15f511c0-c77a-40e9-8cd5-90345022b847:
                                        ID          Name   Age  \
4045  15f511c0-c77a-40e9-8cd5-90345022b847  Amy Johnston  68.0
4045  15f511c0-c77a-40e9-8cd5-90345022b847  Amy Johnston  68.0

                 Email   Join Date     Salary Department
4045  anne74@yahoo.com  2006-05-30  120616.13         HR
4045  anne74@yahoo.com  2020-01-13  118299.00         HR


Duplicate rows for ID 162d1554-81c9-4ec2-9e07-e07372dbee99:
                                        ID                Name   Age Email  \
2543  162d1554-81c9-4ec2-9e07-e07372dbee99  Shannon Ryanothers  90.0  None
2543  162d1554-81c9-4ec2-9e07-e07372dbee99  Shannon Ryanothers  90.0  None

       Join Date   Salary Department
2543  2021-12-24  45024.0    Support
2543  2021-12-24  44944.5    Support


Duplicate rows for ID 1680e251-597a-4954-877a-789ce13e975d:
                                        ID               Name   Age  \
5430  1680e251-597a-4954-877a-789ce13e975d  William Hernandez  37.0
5430  1680e251-597a-4954-877a-789ce13e975d  William Hernandez  37.0

                     Email   Join Date    Salary Department
5430  kristina66@gmail.com  2023-05-16  101798.0      Sales
5430  kristina66@gmail.com  1980-04-05  101798.0      Sales


Duplicate rows for ID 172aacb4-6142-4e2f-b6c9-a6b4a94b0b21:
                                       ID            Name   Age  \
490  172aacb4-6142-4e2f-b6c9-a6b4a94b0b21  Melinda Murphy  33.0
490  172aacb4-6142-4e2f-b6c9-a6b4a94b0b21  Melinda Murphy  33.0

                   Email   Join Date     Salary Department
490  bakerchad@yahoo.com  2021-05-17  139178.00      Sales
490  bakerchad@yahoo.com  2021-05-17  153255.22      Sales


Duplicate rows for ID 1759df8c-3f9b-4963-854f-c9023b076b3b:
                                      ID         Name   Age  \
89  1759df8c-3f9b-4963-854f-c9023b076b3b  Karen Chase  44.0
89  1759df8c-3f9b-4963-854f-c9023b076b3b  Karen Chase  44.0

                   Email   Join Date    Salary Department
89  daniel56@hotmail.com  2020-11-07  122501.3    Support

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9355 entries, 0 to 7648
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          9355 non-null   object
 1   Name        9355 non-null   object
 2   Age         8896 non-null   float64
 3   Email       4505 non-null   object
 4   Join Date   8485 non-null   object
 5   Salary      8439 non-null   float64
 6   Department  8405 non-null   object
dtypes: float64(2), object(5)
memory usage: 584.7+ KB

In [45]:
# function to fill column with valid value 
def fill_unknown_or_nan(x):
    valid_values = x.dropna()[x.dropna() != 'Unknown']
    if not valid_values.empty:
        return x.fillna(valid_values.iloc[0]).replace('Unknown', valid_values.iloc[0])
    return x  # Return unchanged if no valid value exists

In [46]:
data['Age'] = data.groupby(['ID', 'Name'])['Age'].transform(fill_unknown_or_nan)

In [47]:
data['Email'] = data.groupby(['ID', 'Name'])['Email'].transform(fill_unknown_or_nan)

In [48]:
data['Join Date'] = data.groupby(['ID', 'Name'])['Join Date'].transform(fill_unknown_or_nan)

In [49]:
data['Salary'] = data.groupby(['ID', 'Name'])['Salary'].transform(fill_unknown_or_nan)

In [50]:
data['Department'] = data.groupby(['ID', 'Name'])['Department'].transform(fill_unknown_or_nan)

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9355 entries, 0 to 7648
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          9355 non-null   object
 1   Name        9355 non-null   object
 2   Age         8896 non-null   float64
 3   Email       4506 non-null   object
 4   Join Date   8485 non-null   object
 5   Salary      8439 non-null   float64
 6   Department  8405 non-null   object
dtypes: float64(2), object(5)
memory usage: 584.7+ KB

In [52]:
data['ID'].nunique()

8908

In [53]:
data.describe()

               Age         Salary
count  8896.000000    8439.000000
mean     54.180755   89911.220575
std      21.086965   34860.820766
min      18.000000   24655.140000
25%      36.000000   59840.770000
50%      54.000000   89347.000000
75%      72.000000  119406.000000
max      90.000000  176156.210000

In [54]:
data.shape

(9355, 7)

In [55]:
duplicate_value()

Duplicate rows for ID 0053781e-61aa-423e-ae39-adc1ee24f24c:
                                        ID           Name   Age Email  \
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0  None
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0  None

       Join Date    Salary Department
1009  2020-02-23  140100.0  Marketing
1009  2022-01-02  140100.0  Marketing


Duplicate rows for ID 00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e:
                                        ID          Name   Age Email  \
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0  None
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0  None

       Join Date   Salary Department
7942  1991-08-13  63500.0  Marketing
7942  2020-03-17  63500.0  Marketing


Duplicate rows for ID 00d23202-87b8-49bf-bec4-deea25ca43f4:
                                        ID                  Name   Age Email  \
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0  None
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0  None

     Join Date    Salary Department
9851       NaN  36948.17         HR
9851       NaN  44371.00         HR


Duplicate rows for ID 019f2dce-1c6b-48a3-975a-b5fc0f524662:
                                        ID                Name   Age Email  \
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0  None
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0  None

       Join Date     Salary Department
6302  2020-06-20  108294.68  Marketing
6302  2020-06-20  110313.00  Marketing


Duplicate rows for ID 02d6256d-a177-46b6-aaf8-6e18063336e5:
                                       ID     Name   Age                Email  \
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com

      Join Date    Salary Department
939  2023-08-16  140138.0         HR
939  2006-07-10  140138.0         HR


Duplicate rows for ID 02db9c6e-d4fc-4321-9556-11b01bb12bb9:
                                       ID            Name   Age Email  \
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0  None
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0  None

      Join Date  Salary Department
587  1989-01-08     NaN    Support
587  1970-06-19     NaN    Support


Duplicate rows for ID 030bc551-1402-43cb-85dc-2f06ea968a4c:
                                        ID           Name   Age  \
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0

                           Email   Join Date   Salary Department
7402  gutierrezcrystal@gmail.com  1986-11-03  54228.0      Sales
7402  gutierrezcrystal@gmail.com  2023-02-01  54228.0      Sales


Duplicate rows for ID 0384957f-6bde-4234-a5b2-6e63be63170a:
                                        ID             Name   Age Email  \
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0  None
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0  None

       Join Date     Salary Department
7122  2020-08-18  145001.00      Sales
7122  1985-12-26  123249.83      Sales


Duplicate rows for ID 03aeb412-3c27-435f-a878-d86a76f0085e:
                                        ID              Name   Age Email  \
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0  None
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0  None

       Join Date     Salary   Department
9979  2020-07-26  108725.00  Engineering
9979  2020-07-26  126650.23  Engineering


Duplicate rows for ID 0413800c-975f-4107-908c-f9f733496b3c:
                                        ID         Name   Age Email Join Date  \
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0  None       NaN
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0  None       NaN

        Salary Department
8410  56011.00         HR
8410  58724.83         HR


Duplicate rows for ID 04ac7c93-4d85-400a-9cfe-b8155e26aa68:
                                        ID         Name   Age  \
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0

                        Email   Join Date    Salary Department
7330  wrightmatthew@gmail.com  2021-08-18   90211.5      Sales
7330  wrightmatthew@gmail.com  2021-08-18  112474.0      Sales


Duplicate rows for ID 04cc2159-52ce-446c-bb83-10d4ec32b30a:
                                       ID           Name   Age  \
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0

                          Email   Join Date     Salary Department
303  jeffreyhernandez@yahoo.com  2021-04-17  144887.00    Support
303  jeffreyhernandez@yahoo.com  2021-04-17  173539.45    Support


Duplicate rows for ID 05c7d64e-0fec-44ee-88fe-eb3d3621e572:
                                        ID              Name   Age  \
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0

                       Email   Join Date     Salary Department
3866  delgadobobby@gmail.com  2020-04-29  121422.28    Support
3866  delgadobobby@gmail.com  2020-04-29  107416.00    Support


Duplicate rows for ID 07638d51-1811-433a-b883-63e93aeab3eb:
                                        ID            Name   Age  \
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0

                     Email   Join Date  Salary Department
9224  katiecombs@yahoo.com  1985-08-17     NaN    Support
9224  katiecombs@yahoo.com  2023-09-23     NaN    Support


Duplicate rows for ID 07ca0c58-b7b2-47a0-912e-f3ffb5eb6351:
                                        ID           Name   Age  \
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0

                         Email   Join Date     Salary Department
9486  michellemosley@gmail.com  2022-11-09  153498.14  Marketing
9486  michellemosley@gmail.com  2022-11-09  145417.00  Marketing


Duplicate rows for ID 080400bb-3bcf-4880-bb24-dc3a23584b33:
                                        ID        Name   Age  \
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0

                        Email   Join Date   Salary Department
9309  melissawilson@yahoo.com  2022-10-28  62200.0        NaN
9309  melissawilson@yahoo.com  2022-05-14  62200.0        NaN


Duplicate rows for ID 081b1c6d-9dfe-473c-96a2-ec770fcdb61c:
                                        ID            Name   Age  \
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0

                     Email   Join Date   Salary Department
4861  jennifer35@yahoo.com  2020-07-21  81532.0        NaN
4861  jennifer35@yahoo.com  1970-11-12  81532.0        NaN


Duplicate rows for ID 09582335-b0bc-46b2-81a8-e7bf0439b4d0:
                                        ID           Name   Age  \
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0

                        Email   Join Date    Salary Department
9842  nicholekelley@yahoo.com  1970-02-18  139179.0      Sales
9842  nicholekelley@yahoo.com  2001-09-12  139179.0      Sales


Duplicate rows for ID 0a556cb2-ed1c-42ea-8462-6b9b3e18ec16:
                                        ID     Name   Age  \
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0

                    Email   Join Date   Salary   Department
7162  breanna49@yahoo.com  1995-11-21  46931.0  Engineering
7162  breanna49@yahoo.com  2020-04-28  46931.0  Engineering


Duplicate rows for ID 0b7ea886-cc5b-418a-bd15-cc003d6c53b2:
                                        ID         Name   Age Email Join Date  \
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0  None       NaN
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0  None       NaN

        Salary Department
3115  96594.00      Sales
3115  77298.04      Sales


Duplicate rows for ID 0bf01dfc-44ca-444b-9123-47f08b1491cc:
                                        ID          Name   Age  \
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0

                        Email Join Date     Salary Department
3783  christopher54@gmail.com       NaN  132066.00    Support
3783  christopher54@gmail.com       NaN  133919.41    Support


Duplicate rows for ID 0c9f393a-9dae-4a85-9a2d-a11da100d90a:
                                        ID              Name   Age  \
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0

                    Email   Join Date   Salary Department
8302  cgaines@hotmail.com  2023-08-19  89861.0    Support
8302  cgaines@hotmail.com  1991-02-18  89861.0    Support


Duplicate rows for ID 0e8efa97-33ca-4b0d-b234-6d818dfe6008:
                                        ID         Name   Age Email  \
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0  None
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0  None

       Join Date    Salary Department
5711  2000-06-04  144565.0  Marketing
5711  2004-11-13  144565.0  Marketing


Duplicate rows for ID 0f6d137c-fd37-4689-b951-ac0c5efc26b5:
                                        ID           Name   Age  \
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0

                        Email   Join Date   Salary Department
7235  tiffanycooper@yahoo.com  2020-01-13  85101.0    Support
7235  tiffanycooper@yahoo.com  1982-12-21  85101.0    Support


Duplicate rows for ID 0ff202a5-e9d9-42b1-8a1c-b46ec8575d99:
                                       ID            Name   Age Email  \
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0  None
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0  None

      Join Date     Salary   Department
646  2022-06-01  145991.14  Engineering
646  2022-06-01  142446.00  Engineering


Duplicate rows for ID 10944e3d-1a81-4df5-8f75-b5ae1fc3e461:
                                        ID         Name   Age  \
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0

                      Email   Join Date     Salary   Department
8763  qwilliams@hotmail.com  2021-03-04  125692.59  Engineering
8763  qwilliams@hotmail.com  2021-03-04  133695.08  Engineering


Duplicate rows for ID 109a7c13-ebde-4749-8229-5b408d340a29:
                                        ID              Name   Age  \
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0

                        Email   Join Date   Salary Department
9721  karenphelps@hotmail.com  2023-04-14  94134.0        NaN
9721  karenphelps@hotmail.com  1981-02-13  94134.0        NaN


Duplicate rows for ID 10a30c02-789f-41c2-b184-e47108a71303:
                                        ID        Name   Age  \
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0

                           Email   Join Date    Salary Department
7848  turnerkimberly@hotmail.com  1971-12-30  35918.00      Sales
7848  turnerkimberly@hotmail.com  2022-10-06  42330.31      Sales


Duplicate rows for ID 10c26512-ce3a-4387-b71a-47768503562e:
                                        ID               Name   Age  \
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0

                Email   Join Date    Salary Department
3317  rmccoy@hall.com  2020-06-11  62967.69  Marketing
3317  rmccoy@hall.com  2020-06-11  60950.50  Marketing


Duplicate rows for ID 116e5e89-b6d1-4c0c-bf9e-a7db34d70188:
                                        ID             Name   Age Email  \
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0  None
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0  None

       Join Date    Salary Department
1574  2023-08-06  67498.14      Sales
1574  2023-08-06  62308.00      Sales


Duplicate rows for ID 1186cdff-ef30-453c-9b73-d586383a60ad:
                                        ID        Name   Age Email  \
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0  None
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0  None

       Join Date    Salary Department
9752  1973-10-15  145859.0  Marketing
9752  2021-06-02  145859.0  Marketing


Duplicate rows for ID 11a0a2ac-31d3-4dae-98fb-4e3f4d95da65:
                                       ID          Name   Age Email Join Date  \
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0  None       NaN
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0  None       NaN

        Salary Department
472  103412.01      Sales
472  101631.00      Sales


Duplicate rows for ID 126d1500-9869-44ae-92c4-c818a2b57d93:
                                        ID          Name   Age Email  \
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0  None
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0  None

       Join Date    Salary Department
6732  2021-06-08  113129.0         HR
6732  1976-09-03  113129.0         HR


Duplicate rows for ID 12a7c52d-bb72-409f-b3d7-4232aa3f0a34:
                                        ID               Name   Age  \
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0

                     Email   Join Date     Salary Department
7249  claireross@gmail.com  2022-04-07  109754.14    Support
7249  claireross@gmail.com  2022-04-07   94493.00    Support


Duplicate rows for ID 12dde7ca-6754-4a28-81c1-ff8adaf39365:
                                        ID           Name   Age Email  \
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0  None
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0  None

       Join Date    Salary Department
7652  1975-08-09  87262.43         HR
7652  2022-09-16  76189.81         HR


Duplicate rows for ID 1351ae68-3605-48fd-8cc2-e88d9d990d1d:
                                        ID         Name   Age Email  \
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0  None
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0  None

       Join Date   Salary Department
4945  2020-03-12  63094.0    Support
4945  2004-02-07  63094.0    Support


Duplicate rows for ID 135232d5-4e2e-46d5-82b4-47a622b911f5:
                                        ID             Name   Age  \
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0

                    Email   Join Date   Salary Department
9049  tyler40@hotmail.com  1978-02-26  46881.0    Support
9049  tyler40@hotmail.com  2022-01-29  46881.0    Support


Duplicate rows for ID 13552825-66be-49cd-85bc-f1d117290c9f:
                                        ID     Name   Age Email   Join Date  \
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  None  2021-08-26
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  None  2021-08-26

        Salary Department
6835  75630.35  Marketing
6835  79636.00  Marketing


Duplicate rows for ID 13a4ee07-a58a-4a2b-a249-8cec5e256e58:
                                        ID             Name   Age  \
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0

                         Email   Join Date   Salary Department
7276  delgadojeffrey@yahoo.com  2022-06-08  62183.0         HR
7276  delgadojeffrey@yahoo.com  2022-03-16  62183.0         HR


Duplicate rows for ID 14452655-08d2-4698-8498-74f30a5e9f9f:
                                        ID     Name   Age Email   Join Date  \
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  None  1979-06-19
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  None  2021-02-26

         Salary Department
1877  144339.00    Support
1877  144311.66    Support


Duplicate rows for ID 144c46e8-f964-4374-96aa-ead07b754888:
                                        ID              Name   Age  \
3505  144c46e8-f964-4374-96aa-ead07b754888  Brandon Gonzalez  83.0
3505  144c46e8-f964-4374-96aa-ead07b754888  Brandon Gonzalez  83.0

                 Email Join Date    Salary Department
3505  dawn30@gmail.com       NaN  60280.00         HR
3505  dawn30@gmail.com       NaN  51886.35         HR


Duplicate rows for ID 153493fc-efe1-4530-8b3d-7f2c2518796b:
                                        ID          Name   Age Email  \
9214  153493fc-efe1-4530-8b3d-7f2c2518796b  Megan Nguyen  83.0  None
9214  153493fc-efe1-4530-8b3d-7f2c2518796b  Megan Nguyen  83.0  None

       Join Date    Salary   Department
9214  2020-02-18  92976.04  Engineering
9214  2020-02-18  80220.00  Engineering


Duplicate rows for ID 15352b0d-8c4e-4f4d-a16b-9f94e62fe7af:
                                       ID       Name   Age  \
623  15352b0d-8c4e-4f4d-a16b-9f94e62fe7af  Amy Clark  48.0
623  15352b0d-8c4e-4f4d-a16b-9f94e62fe7af  Amy Clark  48.0

                    Email   Join Date  Salary   Department
623  jonessusan@gmail.com  2017-07-11     NaN  Engineering
623  jonessusan@gmail.com  2023-04-23     NaN  Engineering


Duplicate rows for ID 15f511c0-c77a-40e9-8cd5-90345022b847:
                                        ID          Name   Age  \
4045  15f511c0-c77a-40e9-8cd5-90345022b847  Amy Johnston  68.0
4045  15f511c0-c77a-40e9-8cd5-90345022b847  Amy Johnston  68.0

                 Email   Join Date     Salary Department
4045  anne74@yahoo.com  2006-05-30  120616.13         HR
4045  anne74@yahoo.com  2020-01-13  118299.00         HR


Duplicate rows for ID 162d1554-81c9-4ec2-9e07-e07372dbee99:
                                        ID                Name   Age Email  \
2543  162d1554-81c9-4ec2-9e07-e07372dbee99  Shannon Ryanothers  90.0  None
2543  162d1554-81c9-4ec2-9e07-e07372dbee99  Shannon Ryanothers  90.0  None

       Join Date   Salary Department
2543  2021-12-24  45024.0    Support
2543  2021-12-24  44944.5    Support


Duplicate rows for ID 1680e251-597a-4954-877a-789ce13e975d:
                                        ID               Name   Age  \
5430  1680e251-597a-4954-877a-789ce13e975d  William Hernandez  37.0
5430  1680e251-597a-4954-877a-789ce13e975d  William Hernandez  37.0

                     Email   Join Date    Salary Department
5430  kristina66@gmail.com  2023-05-16  101798.0      Sales
5430  kristina66@gmail.com  1980-04-05  101798.0      Sales


Duplicate rows for ID 172aacb4-6142-4e2f-b6c9-a6b4a94b0b21:
                                       ID            Name   Age  \
490  172aacb4-6142-4e2f-b6c9-a6b4a94b0b21  Melinda Murphy  33.0
490  172aacb4-6142-4e2f-b6c9-a6b4a94b0b21  Melinda Murphy  33.0

                   Email   Join Date     Salary Department
490  bakerchad@yahoo.com  2021-05-17  139178.00      Sales
490  bakerchad@yahoo.com  2021-05-17  153255.22      Sales


Duplicate rows for ID 1759df8c-3f9b-4963-854f-c9023b076b3b:
                                      ID         Name   Age  \
89  1759df8c-3f9b-4963-854f-c9023b076b3b  Karen Chase  44.0
89  1759df8c-3f9b-4963-854f-c9023b076b3b  Karen Chase  44.0

                   Email   Join Date    Salary Department
89  daniel56@hotmail.com  2020-11-07  122501.3    Support

In [56]:
data['Email']=data['Email'].fillna('unknown@domain.com')

In [57]:
data=data.drop_duplicates()

In [58]:
data.shape

(9355, 7)

In [59]:
duplicate_value()

Duplicate rows for ID 0053781e-61aa-423e-ae39-adc1ee24f24c:
                                        ID           Name   Age  \
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0

                   Email   Join Date    Salary Department
1009  unknown@domain.com  2020-02-23  140100.0  Marketing
1009  unknown@domain.com  2022-01-02  140100.0  Marketing


Duplicate rows for ID 00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e:
                                        ID          Name   Age  \
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0

                   Email   Join Date   Salary Department
7942  unknown@domain.com  1991-08-13  63500.0  Marketing
7942  unknown@domain.com  2020-03-17  63500.0  Marketing


Duplicate rows for ID 00d23202-87b8-49bf-bec4-deea25ca43f4:
                                        ID                  Name   Age  \
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0

                   Email Join Date    Salary Department
9851  unknown@domain.com       NaN  36948.17         HR
9851  unknown@domain.com       NaN  44371.00         HR


Duplicate rows for ID 019f2dce-1c6b-48a3-975a-b5fc0f524662:
                                        ID                Name   Age  \
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0

                   Email   Join Date     Salary Department
6302  unknown@domain.com  2020-06-20  108294.68  Marketing
6302  unknown@domain.com  2020-06-20  110313.00  Marketing


Duplicate rows for ID 02d6256d-a177-46b6-aaf8-6e18063336e5:
                                       ID     Name   Age                Email  \
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com

      Join Date    Salary Department
939  2023-08-16  140138.0         HR
939  2006-07-10  140138.0         HR


Duplicate rows for ID 02db9c6e-d4fc-4321-9556-11b01bb12bb9:
                                       ID            Name   Age  \
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0

                  Email   Join Date  Salary Department
587  unknown@domain.com  1989-01-08     NaN    Support
587  unknown@domain.com  1970-06-19     NaN    Support


Duplicate rows for ID 030bc551-1402-43cb-85dc-2f06ea968a4c:
                                        ID           Name   Age  \
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0

                           Email   Join Date   Salary Department
7402  gutierrezcrystal@gmail.com  1986-11-03  54228.0      Sales
7402  gutierrezcrystal@gmail.com  2023-02-01  54228.0      Sales


Duplicate rows for ID 0384957f-6bde-4234-a5b2-6e63be63170a:
                                        ID             Name   Age  \
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0

                   Email   Join Date     Salary Department
7122  unknown@domain.com  2020-08-18  145001.00      Sales
7122  unknown@domain.com  1985-12-26  123249.83      Sales


Duplicate rows for ID 03aeb412-3c27-435f-a878-d86a76f0085e:
                                        ID              Name   Age  \
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0

                   Email   Join Date     Salary   Department
9979  unknown@domain.com  2020-07-26  108725.00  Engineering
9979  unknown@domain.com  2020-07-26  126650.23  Engineering


Duplicate rows for ID 0413800c-975f-4107-908c-f9f733496b3c:
                                        ID         Name   Age  \
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0

                   Email Join Date    Salary Department
8410  unknown@domain.com       NaN  56011.00         HR
8410  unknown@domain.com       NaN  58724.83         HR


Duplicate rows for ID 04ac7c93-4d85-400a-9cfe-b8155e26aa68:
                                        ID         Name   Age  \
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0

                        Email   Join Date    Salary Department
7330  wrightmatthew@gmail.com  2021-08-18   90211.5      Sales
7330  wrightmatthew@gmail.com  2021-08-18  112474.0      Sales


Duplicate rows for ID 04cc2159-52ce-446c-bb83-10d4ec32b30a:
                                       ID           Name   Age  \
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0

                          Email   Join Date     Salary Department
303  jeffreyhernandez@yahoo.com  2021-04-17  144887.00    Support
303  jeffreyhernandez@yahoo.com  2021-04-17  173539.45    Support


Duplicate rows for ID 05c7d64e-0fec-44ee-88fe-eb3d3621e572:
                                        ID              Name   Age  \
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0

                       Email   Join Date     Salary Department
3866  delgadobobby@gmail.com  2020-04-29  121422.28    Support
3866  delgadobobby@gmail.com  2020-04-29  107416.00    Support


Duplicate rows for ID 07638d51-1811-433a-b883-63e93aeab3eb:
                                        ID            Name   Age  \
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0

                     Email   Join Date  Salary Department
9224  katiecombs@yahoo.com  1985-08-17     NaN    Support
9224  katiecombs@yahoo.com  2023-09-23     NaN    Support


Duplicate rows for ID 07ca0c58-b7b2-47a0-912e-f3ffb5eb6351:
                                        ID           Name   Age  \
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0

                         Email   Join Date     Salary Department
9486  michellemosley@gmail.com  2022-11-09  153498.14  Marketing
9486  michellemosley@gmail.com  2022-11-09  145417.00  Marketing


Duplicate rows for ID 080400bb-3bcf-4880-bb24-dc3a23584b33:
                                        ID        Name   Age  \
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0

                        Email   Join Date   Salary Department
9309  melissawilson@yahoo.com  2022-10-28  62200.0        NaN
9309  melissawilson@yahoo.com  2022-05-14  62200.0        NaN


Duplicate rows for ID 081b1c6d-9dfe-473c-96a2-ec770fcdb61c:
                                        ID            Name   Age  \
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0

                     Email   Join Date   Salary Department
4861  jennifer35@yahoo.com  2020-07-21  81532.0        NaN
4861  jennifer35@yahoo.com  1970-11-12  81532.0        NaN


Duplicate rows for ID 09582335-b0bc-46b2-81a8-e7bf0439b4d0:
                                        ID           Name   Age  \
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0

                        Email   Join Date    Salary Department
9842  nicholekelley@yahoo.com  1970-02-18  139179.0      Sales
9842  nicholekelley@yahoo.com  2001-09-12  139179.0      Sales


Duplicate rows for ID 0a556cb2-ed1c-42ea-8462-6b9b3e18ec16:
                                        ID     Name   Age  \
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0

                    Email   Join Date   Salary   Department
7162  breanna49@yahoo.com  1995-11-21  46931.0  Engineering
7162  breanna49@yahoo.com  2020-04-28  46931.0  Engineering


Duplicate rows for ID 0b7ea886-cc5b-418a-bd15-cc003d6c53b2:
                                        ID         Name   Age  \
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0

                   Email Join Date    Salary Department
3115  unknown@domain.com       NaN  96594.00      Sales
3115  unknown@domain.com       NaN  77298.04      Sales


Duplicate rows for ID 0bf01dfc-44ca-444b-9123-47f08b1491cc:
                                        ID          Name   Age  \
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0

                        Email Join Date     Salary Department
3783  christopher54@gmail.com       NaN  132066.00    Support
3783  christopher54@gmail.com       NaN  133919.41    Support


Duplicate rows for ID 0c9f393a-9dae-4a85-9a2d-a11da100d90a:
                                        ID              Name   Age  \
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0

                    Email   Join Date   Salary Department
8302  cgaines@hotmail.com  2023-08-19  89861.0    Support
8302  cgaines@hotmail.com  1991-02-18  89861.0    Support


Duplicate rows for ID 0e8efa97-33ca-4b0d-b234-6d818dfe6008:
                                        ID         Name   Age  \
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0

                   Email   Join Date    Salary Department
5711  unknown@domain.com  2000-06-04  144565.0  Marketing
5711  unknown@domain.com  2004-11-13  144565.0  Marketing


Duplicate rows for ID 0f6d137c-fd37-4689-b951-ac0c5efc26b5:
                                        ID           Name   Age  \
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0

                        Email   Join Date   Salary Department
7235  tiffanycooper@yahoo.com  2020-01-13  85101.0    Support
7235  tiffanycooper@yahoo.com  1982-12-21  85101.0    Support


Duplicate rows for ID 0ff202a5-e9d9-42b1-8a1c-b46ec8575d99:
                                       ID            Name   Age  \
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0

                  Email   Join Date     Salary   Department
646  unknown@domain.com  2022-06-01  145991.14  Engineering
646  unknown@domain.com  2022-06-01  142446.00  Engineering


Duplicate rows for ID 10944e3d-1a81-4df5-8f75-b5ae1fc3e461:
                                        ID         Name   Age  \
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0

                      Email   Join Date     Salary   Department
8763  qwilliams@hotmail.com  2021-03-04  125692.59  Engineering
8763  qwilliams@hotmail.com  2021-03-04  133695.08  Engineering


Duplicate rows for ID 109a7c13-ebde-4749-8229-5b408d340a29:
                                        ID              Name   Age  \
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0

                        Email   Join Date   Salary Department
9721  karenphelps@hotmail.com  2023-04-14  94134.0        NaN
9721  karenphelps@hotmail.com  1981-02-13  94134.0        NaN


Duplicate rows for ID 10a30c02-789f-41c2-b184-e47108a71303:
                                        ID        Name   Age  \
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0

                           Email   Join Date    Salary Department
7848  turnerkimberly@hotmail.com  1971-12-30  35918.00      Sales
7848  turnerkimberly@hotmail.com  2022-10-06  42330.31      Sales


Duplicate rows for ID 10c26512-ce3a-4387-b71a-47768503562e:
                                        ID               Name   Age  \
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0

                Email   Join Date    Salary Department
3317  rmccoy@hall.com  2020-06-11  62967.69  Marketing
3317  rmccoy@hall.com  2020-06-11  60950.50  Marketing


Duplicate rows for ID 116e5e89-b6d1-4c0c-bf9e-a7db34d70188:
                                        ID             Name   Age  \
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0

                   Email   Join Date    Salary Department
1574  unknown@domain.com  2023-08-06  67498.14      Sales
1574  unknown@domain.com  2023-08-06  62308.00      Sales


Duplicate rows for ID 1186cdff-ef30-453c-9b73-d586383a60ad:
                                        ID        Name   Age  \
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0

                   Email   Join Date    Salary Department
9752  unknown@domain.com  1973-10-15  145859.0  Marketing
9752  unknown@domain.com  2021-06-02  145859.0  Marketing


Duplicate rows for ID 11a0a2ac-31d3-4dae-98fb-4e3f4d95da65:
                                       ID          Name   Age  \
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0

                  Email Join Date     Salary Department
472  unknown@domain.com       NaN  103412.01      Sales
472  unknown@domain.com       NaN  101631.00      Sales


Duplicate rows for ID 126d1500-9869-44ae-92c4-c818a2b57d93:
                                        ID          Name   Age  \
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0

                   Email   Join Date    Salary Department
6732  unknown@domain.com  2021-06-08  113129.0         HR
6732  unknown@domain.com  1976-09-03  113129.0         HR


Duplicate rows for ID 12a7c52d-bb72-409f-b3d7-4232aa3f0a34:
                                        ID               Name   Age  \
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0

                     Email   Join Date     Salary Department
7249  claireross@gmail.com  2022-04-07  109754.14    Support
7249  claireross@gmail.com  2022-04-07   94493.00    Support


Duplicate rows for ID 12dde7ca-6754-4a28-81c1-ff8adaf39365:
                                        ID           Name   Age  \
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0

                   Email   Join Date    Salary Department
7652  unknown@domain.com  1975-08-09  87262.43         HR
7652  unknown@domain.com  2022-09-16  76189.81         HR


Duplicate rows for ID 1351ae68-3605-48fd-8cc2-e88d9d990d1d:
                                        ID         Name   Age  \
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0

                   Email   Join Date   Salary Department
4945  unknown@domain.com  2020-03-12  63094.0    Support
4945  unknown@domain.com  2004-02-07  63094.0    Support


Duplicate rows for ID 135232d5-4e2e-46d5-82b4-47a622b911f5:
                                        ID             Name   Age  \
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0

                    Email   Join Date   Salary Department
9049  tyler40@hotmail.com  1978-02-26  46881.0    Support
9049  tyler40@hotmail.com  2022-01-29  46881.0    Support


Duplicate rows for ID 13552825-66be-49cd-85bc-f1d117290c9f:
                                        ID     Name   Age               Email  \
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  unknown@domain.com
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  unknown@domain.com

       Join Date    Salary Department
6835  2021-08-26  75630.35  Marketing
6835  2021-08-26  79636.00  Marketing


Duplicate rows for ID 13a4ee07-a58a-4a2b-a249-8cec5e256e58:
                                        ID             Name   Age  \
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0

                         Email   Join Date   Salary Department
7276  delgadojeffrey@yahoo.com  2022-06-08  62183.0         HR
7276  delgadojeffrey@yahoo.com  2022-03-16  62183.0         HR


Duplicate rows for ID 14452655-08d2-4698-8498-74f30a5e9f9f:
                                        ID     Name   Age               Email  \
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  unknown@domain.com
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  unknown@domain.com

       Join Date     Salary Department
1877  1979-06-19  144339.00    Support
1877  2021-02-26  144311.66    Support


Duplicate rows for ID 144c46e8-f964-4374-96aa-ead07b754888:
                                        ID              Name   Age  \
3505  144c46e8-f964-4374-96aa-ead07b754888  Brandon Gonzalez  83.0
3505  144c46e8-f964-4374-96aa-ead07b754888  Brandon Gonzalez  83.0

                 Email Join Date    Salary Department
3505  dawn30@gmail.com       NaN  60280.00         HR
3505  dawn30@gmail.com       NaN  51886.35         HR


Duplicate rows for ID 153493fc-efe1-4530-8b3d-7f2c2518796b:
                                        ID          Name   Age  \
9214  153493fc-efe1-4530-8b3d-7f2c2518796b  Megan Nguyen  83.0
9214  153493fc-efe1-4530-8b3d-7f2c2518796b  Megan Nguyen  83.0

                   Email   Join Date    Salary   Department
9214  unknown@domain.com  2020-02-18  92976.04  Engineering
9214  unknown@domain.com  2020-02-18  80220.00  Engineering


Duplicate rows for ID 15352b0d-8c4e-4f4d-a16b-9f94e62fe7af:
                                       ID       Name   Age  \
623  15352b0d-8c4e-4f4d-a16b-9f94e62fe7af  Amy Clark  48.0
623  15352b0d-8c4e-4f4d-a16b-9f94e62fe7af  Amy Clark  48.0

                    Email   Join Date  Salary   Department
623  jonessusan@gmail.com  2017-07-11     NaN  Engineering
623  jonessusan@gmail.com  2023-04-23     NaN  Engineering


Duplicate rows for ID 15f511c0-c77a-40e9-8cd5-90345022b847:
                                        ID          Name   Age  \
4045  15f511c0-c77a-40e9-8cd5-90345022b847  Amy Johnston  68.0
4045  15f511c0-c77a-40e9-8cd5-90345022b847  Amy Johnston  68.0

                 Email   Join Date     Salary Department
4045  anne74@yahoo.com  2006-05-30  120616.13         HR
4045  anne74@yahoo.com  2020-01-13  118299.00         HR


Duplicate rows for ID 162d1554-81c9-4ec2-9e07-e07372dbee99:
                                        ID                Name   Age  \
2543  162d1554-81c9-4ec2-9e07-e07372dbee99  Shannon Ryanothers  90.0
2543  162d1554-81c9-4ec2-9e07-e07372dbee99  Shannon Ryanothers  90.0

                   Email   Join Date   Salary Department
2543  unknown@domain.com  2021-12-24  45024.0    Support
2543  unknown@domain.com  2021-12-24  44944.5    Support


Duplicate rows for ID 1680e251-597a-4954-877a-789ce13e975d:
                                        ID               Name   Age  \
5430  1680e251-597a-4954-877a-789ce13e975d  William Hernandez  37.0
5430  1680e251-597a-4954-877a-789ce13e975d  William Hernandez  37.0

                     Email   Join Date    Salary Department

In [60]:
data['Join Date'] = data['Join Date'].fillna('1900-01-01')

In [61]:
data.shape

(9355, 7)

In [62]:
duplicate_value()

Duplicate rows for ID 0053781e-61aa-423e-ae39-adc1ee24f24c:
                                        ID           Name   Age  \
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0

                   Email   Join Date    Salary Department
1009  unknown@domain.com  2020-02-23  140100.0  Marketing
1009  unknown@domain.com  2022-01-02  140100.0  Marketing


Duplicate rows for ID 00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e:
                                        ID          Name   Age  \
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0

                   Email   Join Date   Salary Department
7942  unknown@domain.com  1991-08-13  63500.0  Marketing
7942  unknown@domain.com  2020-03-17  63500.0  Marketing


Duplicate rows for ID 00d23202-87b8-49bf-bec4-deea25ca43f4:
                                        ID                  Name   Age  \
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0

                   Email   Join Date    Salary Department
9851  unknown@domain.com  1900-01-01  36948.17         HR
9851  unknown@domain.com  1900-01-01  44371.00         HR


Duplicate rows for ID 019f2dce-1c6b-48a3-975a-b5fc0f524662:
                                        ID                Name   Age  \
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0

                   Email   Join Date     Salary Department
6302  unknown@domain.com  2020-06-20  108294.68  Marketing
6302  unknown@domain.com  2020-06-20  110313.00  Marketing


Duplicate rows for ID 02d6256d-a177-46b6-aaf8-6e18063336e5:
                                       ID     Name   Age                Email  \
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com

      Join Date    Salary Department
939  2023-08-16  140138.0         HR
939  2006-07-10  140138.0         HR


Duplicate rows for ID 02db9c6e-d4fc-4321-9556-11b01bb12bb9:
                                       ID            Name   Age  \
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0

                  Email   Join Date  Salary Department
587  unknown@domain.com  1989-01-08     NaN    Support
587  unknown@domain.com  1970-06-19     NaN    Support


Duplicate rows for ID 030bc551-1402-43cb-85dc-2f06ea968a4c:
                                        ID           Name   Age  \
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0

                           Email   Join Date   Salary Department
7402  gutierrezcrystal@gmail.com  1986-11-03  54228.0      Sales
7402  gutierrezcrystal@gmail.com  2023-02-01  54228.0      Sales


Duplicate rows for ID 0384957f-6bde-4234-a5b2-6e63be63170a:
                                        ID             Name   Age  \
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0

                   Email   Join Date     Salary Department
7122  unknown@domain.com  2020-08-18  145001.00      Sales
7122  unknown@domain.com  1985-12-26  123249.83      Sales


Duplicate rows for ID 03aeb412-3c27-435f-a878-d86a76f0085e:
                                        ID              Name   Age  \
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0

                   Email   Join Date     Salary   Department
9979  unknown@domain.com  2020-07-26  108725.00  Engineering
9979  unknown@domain.com  2020-07-26  126650.23  Engineering


Duplicate rows for ID 0413800c-975f-4107-908c-f9f733496b3c:
                                        ID         Name   Age  \
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0

                   Email   Join Date    Salary Department
8410  unknown@domain.com  1900-01-01  56011.00         HR
8410  unknown@domain.com  1900-01-01  58724.83         HR


Duplicate rows for ID 04ac7c93-4d85-400a-9cfe-b8155e26aa68:
                                        ID         Name   Age  \
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0

                        Email   Join Date    Salary Department
7330  wrightmatthew@gmail.com  2021-08-18   90211.5      Sales
7330  wrightmatthew@gmail.com  2021-08-18  112474.0      Sales


Duplicate rows for ID 04cc2159-52ce-446c-bb83-10d4ec32b30a:
                                       ID           Name   Age  \
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0

                          Email   Join Date     Salary Department
303  jeffreyhernandez@yahoo.com  2021-04-17  144887.00    Support
303  jeffreyhernandez@yahoo.com  2021-04-17  173539.45    Support


Duplicate rows for ID 05c7d64e-0fec-44ee-88fe-eb3d3621e572:
                                        ID              Name   Age  \
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0

                       Email   Join Date     Salary Department
3866  delgadobobby@gmail.com  2020-04-29  121422.28    Support
3866  delgadobobby@gmail.com  2020-04-29  107416.00    Support


Duplicate rows for ID 07638d51-1811-433a-b883-63e93aeab3eb:
                                        ID            Name   Age  \
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0

                     Email   Join Date  Salary Department
9224  katiecombs@yahoo.com  1985-08-17     NaN    Support
9224  katiecombs@yahoo.com  2023-09-23     NaN    Support


Duplicate rows for ID 07ca0c58-b7b2-47a0-912e-f3ffb5eb6351:
                                        ID           Name   Age  \
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0

                         Email   Join Date     Salary Department
9486  michellemosley@gmail.com  2022-11-09  153498.14  Marketing
9486  michellemosley@gmail.com  2022-11-09  145417.00  Marketing


Duplicate rows for ID 080400bb-3bcf-4880-bb24-dc3a23584b33:
                                        ID        Name   Age  \
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0

                        Email   Join Date   Salary Department
9309  melissawilson@yahoo.com  2022-10-28  62200.0        NaN
9309  melissawilson@yahoo.com  2022-05-14  62200.0        NaN


Duplicate rows for ID 081b1c6d-9dfe-473c-96a2-ec770fcdb61c:
                                        ID            Name   Age  \
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0

                     Email   Join Date   Salary Department
4861  jennifer35@yahoo.com  2020-07-21  81532.0        NaN
4861  jennifer35@yahoo.com  1970-11-12  81532.0        NaN


Duplicate rows for ID 09582335-b0bc-46b2-81a8-e7bf0439b4d0:
                                        ID           Name   Age  \
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0

                        Email   Join Date    Salary Department
9842  nicholekelley@yahoo.com  1970-02-18  139179.0      Sales
9842  nicholekelley@yahoo.com  2001-09-12  139179.0      Sales


Duplicate rows for ID 0a556cb2-ed1c-42ea-8462-6b9b3e18ec16:
                                        ID     Name   Age  \
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0

                    Email   Join Date   Salary   Department
7162  breanna49@yahoo.com  1995-11-21  46931.0  Engineering
7162  breanna49@yahoo.com  2020-04-28  46931.0  Engineering


Duplicate rows for ID 0b7ea886-cc5b-418a-bd15-cc003d6c53b2:
                                        ID         Name   Age  \
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0

                   Email   Join Date    Salary Department
3115  unknown@domain.com  1900-01-01  96594.00      Sales
3115  unknown@domain.com  1900-01-01  77298.04      Sales


Duplicate rows for ID 0bf01dfc-44ca-444b-9123-47f08b1491cc:
                                        ID          Name   Age  \
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0

                        Email   Join Date     Salary Department
3783  christopher54@gmail.com  1900-01-01  132066.00    Support
3783  christopher54@gmail.com  1900-01-01  133919.41    Support


Duplicate rows for ID 0c9f393a-9dae-4a85-9a2d-a11da100d90a:
                                        ID              Name   Age  \
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0

                    Email   Join Date   Salary Department
8302  cgaines@hotmail.com  2023-08-19  89861.0    Support
8302  cgaines@hotmail.com  1991-02-18  89861.0    Support


Duplicate rows for ID 0e8efa97-33ca-4b0d-b234-6d818dfe6008:
                                        ID         Name   Age  \
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0

                   Email   Join Date    Salary Department
5711  unknown@domain.com  2000-06-04  144565.0  Marketing
5711  unknown@domain.com  2004-11-13  144565.0  Marketing


Duplicate rows for ID 0f6d137c-fd37-4689-b951-ac0c5efc26b5:
                                        ID           Name   Age  \
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0

                        Email   Join Date   Salary Department
7235  tiffanycooper@yahoo.com  2020-01-13  85101.0    Support
7235  tiffanycooper@yahoo.com  1982-12-21  85101.0    Support


Duplicate rows for ID 0ff202a5-e9d9-42b1-8a1c-b46ec8575d99:
                                       ID            Name   Age  \
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0

                  Email   Join Date     Salary   Department
646  unknown@domain.com  2022-06-01  145991.14  Engineering
646  unknown@domain.com  2022-06-01  142446.00  Engineering


Duplicate rows for ID 10944e3d-1a81-4df5-8f75-b5ae1fc3e461:
                                        ID         Name   Age  \
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0

                      Email   Join Date     Salary   Department
8763  qwilliams@hotmail.com  2021-03-04  125692.59  Engineering
8763  qwilliams@hotmail.com  2021-03-04  133695.08  Engineering


Duplicate rows for ID 109a7c13-ebde-4749-8229-5b408d340a29:
                                        ID              Name   Age  \
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0

                        Email   Join Date   Salary Department
9721  karenphelps@hotmail.com  2023-04-14  94134.0        NaN
9721  karenphelps@hotmail.com  1981-02-13  94134.0        NaN


Duplicate rows for ID 10a30c02-789f-41c2-b184-e47108a71303:
                                        ID        Name   Age  \
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0

                           Email   Join Date    Salary Department
7848  turnerkimberly@hotmail.com  1971-12-30  35918.00      Sales
7848  turnerkimberly@hotmail.com  2022-10-06  42330.31      Sales


Duplicate rows for ID 10c26512-ce3a-4387-b71a-47768503562e:
                                        ID               Name   Age  \
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0

                Email   Join Date    Salary Department
3317  rmccoy@hall.com  2020-06-11  62967.69  Marketing
3317  rmccoy@hall.com  2020-06-11  60950.50  Marketing


Duplicate rows for ID 116e5e89-b6d1-4c0c-bf9e-a7db34d70188:
                                        ID             Name   Age  \
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0

                   Email   Join Date    Salary Department
1574  unknown@domain.com  2023-08-06  67498.14      Sales
1574  unknown@domain.com  2023-08-06  62308.00      Sales


Duplicate rows for ID 1186cdff-ef30-453c-9b73-d586383a60ad:
                                        ID        Name   Age  \
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0

                   Email   Join Date    Salary Department
9752  unknown@domain.com  1973-10-15  145859.0  Marketing
9752  unknown@domain.com  2021-06-02  145859.0  Marketing


Duplicate rows for ID 11a0a2ac-31d3-4dae-98fb-4e3f4d95da65:
                                       ID          Name   Age  \
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0

                  Email   Join Date     Salary Department
472  unknown@domain.com  1900-01-01  103412.01      Sales
472  unknown@domain.com  1900-01-01  101631.00      Sales


Duplicate rows for ID 126d1500-9869-44ae-92c4-c818a2b57d93:
                                        ID          Name   Age  \
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0

                   Email   Join Date    Salary Department
6732  unknown@domain.com  2021-06-08  113129.0         HR
6732  unknown@domain.com  1976-09-03  113129.0         HR


Duplicate rows for ID 12a7c52d-bb72-409f-b3d7-4232aa3f0a34:
                                        ID               Name   Age  \
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0

                     Email   Join Date     Salary Department
7249  claireross@gmail.com  2022-04-07  109754.14    Support
7249  claireross@gmail.com  2022-04-07   94493.00    Support


Duplicate rows for ID 12dde7ca-6754-4a28-81c1-ff8adaf39365:
                                        ID           Name   Age  \
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0

                   Email   Join Date    Salary Department
7652  unknown@domain.com  1975-08-09  87262.43         HR
7652  unknown@domain.com  2022-09-16  76189.81         HR


Duplicate rows for ID 1351ae68-3605-48fd-8cc2-e88d9d990d1d:
                                        ID         Name   Age  \
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0

                   Email   Join Date   Salary Department
4945  unknown@domain.com  2020-03-12  63094.0    Support
4945  unknown@domain.com  2004-02-07  63094.0    Support


Duplicate rows for ID 135232d5-4e2e-46d5-82b4-47a622b911f5:
                                        ID             Name   Age  \
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0

                    Email   Join Date   Salary Department
9049  tyler40@hotmail.com  1978-02-26  46881.0    Support
9049  tyler40@hotmail.com  2022-01-29  46881.0    Support


Duplicate rows for ID 13552825-66be-49cd-85bc-f1d117290c9f:
                                        ID     Name   Age               Email  \
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  unknown@domain.com
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  unknown@domain.com

       Join Date    Salary Department
6835  2021-08-26  75630.35  Marketing
6835  2021-08-26  79636.00  Marketing


Duplicate rows for ID 13a4ee07-a58a-4a2b-a249-8cec5e256e58:
                                        ID             Name   Age  \
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0

                         Email   Join Date   Salary Department
7276  delgadojeffrey@yahoo.com  2022-06-08  62183.0         HR
7276  delgadojeffrey@yahoo.com  2022-03-16  62183.0         HR


Duplicate rows for ID 14452655-08d2-4698-8498-74f30a5e9f9f:
                                        ID     Name   Age               Email  \
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  unknown@domain.com
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  unknown@domain.com

       Join Date     Salary Department
1877  1979-06-19  144339.00    Support
1877  2021-02-26  144311.66    Support


Duplicate rows for ID 144c46e8-f964-4374-96aa-ead07b754888:
                                        ID              Name   Age  \
3505  144c46e8-f964-4374-96aa-ead07b754888  Brandon Gonzalez  83.0
3505  144c46e8-f964-4374-96aa-ead07b754888  Brandon Gonzalez  83.0

                 Email   Join Date    Salary Department
3505  dawn30@gmail.com  1900-01-01  60280.00         HR
3505  dawn30@gmail.com  1900-01-01  51886.35         HR


Duplicate rows for ID 153493fc-efe1-4530-8b3d-7f2c2518796b:
                                        ID          Name   Age  \
9214  153493fc-efe1-4530-8b3d-7f2c2518796b  Megan Nguyen  83.0
9214  153493fc-efe1-4530-8b3d-7f2c2518796b  Megan Nguyen  83.0

                   Email   Join Date    Salary   Department
9214  unknown@domain.com  2020-02-18  92976.04  Engineering
9214  unknown@domain.com  2020-02-18  80220.00  Engineering


Duplicate rows for ID 15352b0d-8c4e-4f4d-a16b-9f94e62fe7af:
                                       ID       Name   Age  \
623  15352b0d-8c4e-4f4d-a16b-9f94e62fe7af  Amy Clark  48.0
623  15352b0d-8c4e-4f4d-a16b-9f94e62fe7af  Amy Clark  48.0

                    Email   Join Date  Salary   Department
623  jonessusan@gmail.com  2017-07-11     NaN  Engineering
623  jonessusan@gmail.com  2023-04-23     NaN  Engineering


Duplicate rows for ID 15f511c0-c77a-40e9-8cd5-90345022b847:
                                        ID          Name   Age  \
4045  15f511c0-c77a-40e9-8cd5-90345022b847  Amy Johnston  68.0
4045  15f511c0-c77a-40e9-8cd5-90345022b847  Amy Johnston  68.0

                 Email   Join Date     Salary Department
4045  anne74@yahoo.com  2006-05-30  120616.13         HR
4045  anne74@yahoo.com  2020-01-13  118299.00         HR


Duplicate rows for ID 162d1554-81c9-4ec2-9e07-e07372dbee99:
                                        ID                Name   Age  \
2543  162d1554-81c9-4ec2-9e07-e07372dbee99  Shannon Ryanothers  90.0
2543  162d1554-81c9-4ec2-9e07-e07372dbee99  Shannon Ryanothers  90.0

                   Email   Join Date   Salary Department
2543  unknown@domain.com  2021-12-24  45024.0    Support
2543  unknown@domain.com  2021-12-24  44944.5    Support


Duplicate rows for ID 1680e251-597a-4954-877a-789ce13e975d:
                                        ID               Name   Age  \
5430  1680e251-597a-4954-877a-789ce13e975d  William Hernandez  37.0
5430  1680e251-597a-4954-877a-789ce13e975d  William Hernandez  37.0

                     Email   Join Date    Salary Department

In [63]:
salary_summary = data.groupby('Department')['Salary'].describe()
print(salary_summary)

              count          mean           std       min        25%  \
Department
Engineering  1503.0  89920.439568  35156.767353  26720.41  59567.500
HR           1484.0  88558.390088  35041.775244  26233.92  58547.500
Marketing    1512.0  90267.674921  35198.148744  28192.81  60329.675
Sales        1541.0  91108.733082  34514.722752  27187.98  61024.000
Support      1530.0  90602.548458  34787.107534  24655.14  60862.000

                   50%         75%        max
Department
Engineering  90454.000  119772.500  174786.88
HR           86614.115  117833.015  169568.43
Marketing    89104.500  120299.620  175218.43
Sales        91442.360  120093.000  165560.14
Support      90022.000  120209.000  176156.21

In [64]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9355 entries, 0 to 7648
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          9355 non-null   object
 1   Name        9355 non-null   object
 2   Age         8896 non-null   float64
 3   Email       9355 non-null   object
 4   Join Date   9355 non-null   object
 5   Salary      8439 non-null   float64
 6   Department  8405 non-null   object
dtypes: float64(2), object(5)
memory usage: 584.7+ KB

In [65]:
data['Age']=data['Age'].fillna(data['Age'].median())
data['Salary']=data['Salary'].fillna(data['Salary'].median())
data['Department']=data['Department'].fillna(data['Department'].mode()[0])

In [66]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9355 entries, 0 to 7648
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          9355 non-null   object
 1   Name        9355 non-null   object
 2   Age         9355 non-null   float64
 3   Email       9355 non-null   object
 4   Join Date   9355 non-null   object
 5   Salary      9355 non-null   float64
 6   Department  9355 non-null   object
dtypes: float64(2), object(5)
memory usage: 584.7+ KB

In [67]:
duplicate_value()

Duplicate rows for ID 0053781e-61aa-423e-ae39-adc1ee24f24c:
                                        ID           Name   Age  \
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0
1009  0053781e-61aa-423e-ae39-adc1ee24f24c  Ronald Morgan  43.0

                   Email   Join Date    Salary Department
1009  unknown@domain.com  2020-02-23  140100.0  Marketing
1009  unknown@domain.com  2022-01-02  140100.0  Marketing


Duplicate rows for ID 00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e:
                                        ID          Name   Age  \
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0
7942  00ac2b1c-dcc9-4e5f-a72a-b5c5e0fe092e  Tammy Thomas  83.0

                   Email   Join Date   Salary Department
7942  unknown@domain.com  1991-08-13  63500.0  Marketing
7942  unknown@domain.com  2020-03-17  63500.0  Marketing


Duplicate rows for ID 00d23202-87b8-49bf-bec4-deea25ca43f4:
                                        ID                  Name   Age  \
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0
9851  00d23202-87b8-49bf-bec4-deea25ca43f4  Kelsey Gutierrezwind  41.0

                   Email   Join Date    Salary Department
9851  unknown@domain.com  1900-01-01  36948.17         HR
9851  unknown@domain.com  1900-01-01  44371.00         HR


Duplicate rows for ID 019f2dce-1c6b-48a3-975a-b5fc0f524662:
                                        ID                Name   Age  \
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0
6302  019f2dce-1c6b-48a3-975a-b5fc0f524662  Joshua Wagnerbegin  70.0

                   Email   Join Date     Salary Department
6302  unknown@domain.com  2020-06-20  108294.68  Marketing
6302  unknown@domain.com  2020-06-20  110313.00  Marketing


Duplicate rows for ID 02d6256d-a177-46b6-aaf8-6e18063336e5:
                                       ID     Name   Age                Email  \
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com
939  02d6256d-a177-46b6-aaf8-6e18063336e5  Unknown  21.0  melissa05@gmail.com

      Join Date    Salary Department
939  2023-08-16  140138.0         HR
939  2006-07-10  140138.0         HR


Duplicate rows for ID 02db9c6e-d4fc-4321-9556-11b01bb12bb9:
                                       ID            Name   Age  \
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0
587  02db9c6e-d4fc-4321-9556-11b01bb12bb9  John Baileybad  49.0

                  Email   Join Date   Salary Department
587  unknown@domain.com  1989-01-08  89347.0    Support
587  unknown@domain.com  1970-06-19  89347.0    Support


Duplicate rows for ID 030bc551-1402-43cb-85dc-2f06ea968a4c:
                                        ID           Name   Age  \
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0
7402  030bc551-1402-43cb-85dc-2f06ea968a4c  Michael Patel  25.0

                           Email   Join Date   Salary Department
7402  gutierrezcrystal@gmail.com  1986-11-03  54228.0      Sales
7402  gutierrezcrystal@gmail.com  2023-02-01  54228.0      Sales


Duplicate rows for ID 0384957f-6bde-4234-a5b2-6e63be63170a:
                                        ID             Name   Age  \
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0
7122  0384957f-6bde-4234-a5b2-6e63be63170a  Christine Brown  44.0

                   Email   Join Date     Salary Department
7122  unknown@domain.com  2020-08-18  145001.00      Sales
7122  unknown@domain.com  1985-12-26  123249.83      Sales


Duplicate rows for ID 03aeb412-3c27-435f-a878-d86a76f0085e:
                                        ID              Name   Age  \
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0
9979  03aeb412-3c27-435f-a878-d86a76f0085e  Christopher Todd  72.0

                   Email   Join Date     Salary   Department
9979  unknown@domain.com  2020-07-26  108725.00  Engineering
9979  unknown@domain.com  2020-07-26  126650.23  Engineering


Duplicate rows for ID 0413800c-975f-4107-908c-f9f733496b3c:
                                        ID         Name   Age  \
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0
8410  0413800c-975f-4107-908c-f9f733496b3c  Terry Meyer  19.0

                   Email   Join Date    Salary Department
8410  unknown@domain.com  1900-01-01  56011.00         HR
8410  unknown@domain.com  1900-01-01  58724.83         HR


Duplicate rows for ID 04ac7c93-4d85-400a-9cfe-b8155e26aa68:
                                        ID         Name   Age  \
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0
7330  04ac7c93-4d85-400a-9cfe-b8155e26aa68  Megan Jones  85.0

                        Email   Join Date    Salary Department
7330  wrightmatthew@gmail.com  2021-08-18   90211.5      Sales
7330  wrightmatthew@gmail.com  2021-08-18  112474.0      Sales


Duplicate rows for ID 04cc2159-52ce-446c-bb83-10d4ec32b30a:
                                       ID           Name   Age  \
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0
303  04cc2159-52ce-446c-bb83-10d4ec32b30a  Patrick Oneil  49.0

                          Email   Join Date     Salary Department
303  jeffreyhernandez@yahoo.com  2021-04-17  144887.00    Support
303  jeffreyhernandez@yahoo.com  2021-04-17  173539.45    Support


Duplicate rows for ID 05c7d64e-0fec-44ee-88fe-eb3d3621e572:
                                        ID              Name   Age  \
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0
3866  05c7d64e-0fec-44ee-88fe-eb3d3621e572  Rachael Holloway  60.0

                       Email   Join Date     Salary Department
3866  delgadobobby@gmail.com  2020-04-29  121422.28    Support
3866  delgadobobby@gmail.com  2020-04-29  107416.00    Support


Duplicate rows for ID 07638d51-1811-433a-b883-63e93aeab3eb:
                                        ID            Name   Age  \
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0
9224  07638d51-1811-433a-b883-63e93aeab3eb  Cheyenne Moore  88.0

                     Email   Join Date   Salary Department
9224  katiecombs@yahoo.com  1985-08-17  89347.0    Support
9224  katiecombs@yahoo.com  2023-09-23  89347.0    Support


Duplicate rows for ID 07ca0c58-b7b2-47a0-912e-f3ffb5eb6351:
                                        ID           Name   Age  \
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0
9486  07ca0c58-b7b2-47a0-912e-f3ffb5eb6351  Kevin Vincent  51.0

                         Email   Join Date     Salary Department
9486  michellemosley@gmail.com  2022-11-09  153498.14  Marketing
9486  michellemosley@gmail.com  2022-11-09  145417.00  Marketing


Duplicate rows for ID 080400bb-3bcf-4880-bb24-dc3a23584b33:
                                        ID        Name   Age  \
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0
9309  080400bb-3bcf-4880-bb24-dc3a23584b33  Jenna Rowe  80.0

                        Email   Join Date   Salary Department
9309  melissawilson@yahoo.com  2022-10-28  62200.0      Sales
9309  melissawilson@yahoo.com  2022-05-14  62200.0      Sales


Duplicate rows for ID 081b1c6d-9dfe-473c-96a2-ec770fcdb61c:
                                        ID            Name   Age  \
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0
4861  081b1c6d-9dfe-473c-96a2-ec770fcdb61c  Phillip Lozano  87.0

                     Email   Join Date   Salary Department
4861  jennifer35@yahoo.com  2020-07-21  81532.0      Sales
4861  jennifer35@yahoo.com  1970-11-12  81532.0      Sales


Duplicate rows for ID 09582335-b0bc-46b2-81a8-e7bf0439b4d0:
                                        ID           Name   Age  \
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0
9842  09582335-b0bc-46b2-81a8-e7bf0439b4d0  Kathleen Diaz  53.0

                        Email   Join Date    Salary Department
9842  nicholekelley@yahoo.com  1970-02-18  139179.0      Sales
9842  nicholekelley@yahoo.com  2001-09-12  139179.0      Sales


Duplicate rows for ID 0a556cb2-ed1c-42ea-8462-6b9b3e18ec16:
                                        ID     Name   Age  \
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0
7162  0a556cb2-ed1c-42ea-8462-6b9b3e18ec16  Unknown  47.0

                    Email   Join Date   Salary   Department
7162  breanna49@yahoo.com  1995-11-21  46931.0  Engineering
7162  breanna49@yahoo.com  2020-04-28  46931.0  Engineering


Duplicate rows for ID 0b7ea886-cc5b-418a-bd15-cc003d6c53b2:
                                        ID         Name   Age  \
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0
3115  0b7ea886-cc5b-418a-bd15-cc003d6c53b2  Kevin Baker  52.0

                   Email   Join Date    Salary Department
3115  unknown@domain.com  1900-01-01  96594.00      Sales
3115  unknown@domain.com  1900-01-01  77298.04      Sales


Duplicate rows for ID 0bf01dfc-44ca-444b-9123-47f08b1491cc:
                                        ID          Name   Age  \
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0
3783  0bf01dfc-44ca-444b-9123-47f08b1491cc  Joseph Jones  43.0

                        Email   Join Date     Salary Department
3783  christopher54@gmail.com  1900-01-01  132066.00    Support
3783  christopher54@gmail.com  1900-01-01  133919.41    Support


Duplicate rows for ID 0c9f393a-9dae-4a85-9a2d-a11da100d90a:
                                        ID              Name   Age  \
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0
8302  0c9f393a-9dae-4a85-9a2d-a11da100d90a  Stephanie Warner  86.0

                    Email   Join Date   Salary Department
8302  cgaines@hotmail.com  2023-08-19  89861.0    Support
8302  cgaines@hotmail.com  1991-02-18  89861.0    Support


Duplicate rows for ID 0e8efa97-33ca-4b0d-b234-6d818dfe6008:
                                        ID         Name   Age  \
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0
5711  0e8efa97-33ca-4b0d-b234-6d818dfe6008  Terri White  53.0

                   Email   Join Date    Salary Department
5711  unknown@domain.com  2000-06-04  144565.0  Marketing
5711  unknown@domain.com  2004-11-13  144565.0  Marketing


Duplicate rows for ID 0f6d137c-fd37-4689-b951-ac0c5efc26b5:
                                        ID           Name   Age  \
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0
7235  0f6d137c-fd37-4689-b951-ac0c5efc26b5  Gary Thornton  67.0

                        Email   Join Date   Salary Department
7235  tiffanycooper@yahoo.com  2020-01-13  85101.0    Support
7235  tiffanycooper@yahoo.com  1982-12-21  85101.0    Support


Duplicate rows for ID 0ff202a5-e9d9-42b1-8a1c-b46ec8575d99:
                                       ID            Name   Age  \
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0
646  0ff202a5-e9d9-42b1-8a1c-b46ec8575d99  Jeffrey Medina  36.0

                  Email   Join Date     Salary   Department
646  unknown@domain.com  2022-06-01  145991.14  Engineering
646  unknown@domain.com  2022-06-01  142446.00  Engineering


Duplicate rows for ID 10944e3d-1a81-4df5-8f75-b5ae1fc3e461:
                                        ID         Name   Age  \
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0
8763  10944e3d-1a81-4df5-8f75-b5ae1fc3e461  Gary Waters  83.0

                      Email   Join Date     Salary   Department
8763  qwilliams@hotmail.com  2021-03-04  125692.59  Engineering
8763  qwilliams@hotmail.com  2021-03-04  133695.08  Engineering


Duplicate rows for ID 109a7c13-ebde-4749-8229-5b408d340a29:
                                        ID              Name   Age  \
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0
9721  109a7c13-ebde-4749-8229-5b408d340a29  Heather Matthews  20.0

                        Email   Join Date   Salary Department
9721  karenphelps@hotmail.com  2023-04-14  94134.0      Sales
9721  karenphelps@hotmail.com  1981-02-13  94134.0      Sales


Duplicate rows for ID 10a30c02-789f-41c2-b184-e47108a71303:
                                        ID        Name   Age  \
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0
7848  10a30c02-789f-41c2-b184-e47108a71303  Emma Adams  81.0

                           Email   Join Date    Salary Department
7848  turnerkimberly@hotmail.com  1971-12-30  35918.00      Sales
7848  turnerkimberly@hotmail.com  2022-10-06  42330.31      Sales


Duplicate rows for ID 10c26512-ce3a-4387-b71a-47768503562e:
                                        ID               Name   Age  \
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0
3317  10c26512-ce3a-4387-b71a-47768503562e  Kimberly Cummings  54.0

                Email   Join Date    Salary Department
3317  rmccoy@hall.com  2020-06-11  62967.69  Marketing
3317  rmccoy@hall.com  2020-06-11  60950.50  Marketing


Duplicate rows for ID 116e5e89-b6d1-4c0c-bf9e-a7db34d70188:
                                        ID             Name   Age  \
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0
1574  116e5e89-b6d1-4c0c-bf9e-a7db34d70188  Taylor Morrison  78.0

                   Email   Join Date    Salary Department
1574  unknown@domain.com  2023-08-06  67498.14      Sales
1574  unknown@domain.com  2023-08-06  62308.00      Sales


Duplicate rows for ID 1186cdff-ef30-453c-9b73-d586383a60ad:
                                        ID        Name   Age  \
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0
9752  1186cdff-ef30-453c-9b73-d586383a60ad  Ashley Lee  22.0

                   Email   Join Date    Salary Department
9752  unknown@domain.com  1973-10-15  145859.0  Marketing
9752  unknown@domain.com  2021-06-02  145859.0  Marketing


Duplicate rows for ID 11a0a2ac-31d3-4dae-98fb-4e3f4d95da65:
                                       ID          Name   Age  \
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0
472  11a0a2ac-31d3-4dae-98fb-4e3f4d95da65  Erika Farrel  84.0

                  Email   Join Date     Salary Department
472  unknown@domain.com  1900-01-01  103412.01      Sales
472  unknown@domain.com  1900-01-01  101631.00      Sales


Duplicate rows for ID 126d1500-9869-44ae-92c4-c818a2b57d93:
                                        ID          Name   Age  \
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0
6732  126d1500-9869-44ae-92c4-c818a2b57d93  Dave Jimenez  85.0

                   Email   Join Date    Salary Department
6732  unknown@domain.com  2021-06-08  113129.0         HR
6732  unknown@domain.com  1976-09-03  113129.0         HR


Duplicate rows for ID 12a7c52d-bb72-409f-b3d7-4232aa3f0a34:
                                        ID               Name   Age  \
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0
7249  12a7c52d-bb72-409f-b3d7-4232aa3f0a34  Christine Roberts  35.0

                     Email   Join Date     Salary Department
7249  claireross@gmail.com  2022-04-07  109754.14    Support
7249  claireross@gmail.com  2022-04-07   94493.00    Support


Duplicate rows for ID 12dde7ca-6754-4a28-81c1-ff8adaf39365:
                                        ID           Name   Age  \
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0
7652  12dde7ca-6754-4a28-81c1-ff8adaf39365  Frank Mitchel  73.0

                   Email   Join Date    Salary Department
7652  unknown@domain.com  1975-08-09  87262.43         HR
7652  unknown@domain.com  2022-09-16  76189.81         HR


Duplicate rows for ID 1351ae68-3605-48fd-8cc2-e88d9d990d1d:
                                        ID         Name   Age  \
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0
4945  1351ae68-3605-48fd-8cc2-e88d9d990d1d  Kelly Johns  86.0

                   Email   Join Date   Salary Department
4945  unknown@domain.com  2020-03-12  63094.0    Support
4945  unknown@domain.com  2004-02-07  63094.0    Support


Duplicate rows for ID 135232d5-4e2e-46d5-82b4-47a622b911f5:
                                        ID             Name   Age  \
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0
9049  135232d5-4e2e-46d5-82b4-47a622b911f5  Timothy Kennedy  78.0

                    Email   Join Date   Salary Department
9049  tyler40@hotmail.com  1978-02-26  46881.0    Support
9049  tyler40@hotmail.com  2022-01-29  46881.0    Support


Duplicate rows for ID 13552825-66be-49cd-85bc-f1d117290c9f:
                                        ID     Name   Age               Email  \
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  unknown@domain.com
6835  13552825-66be-49cd-85bc-f1d117290c9f  Unknown  57.0  unknown@domain.com

       Join Date    Salary Department
6835  2021-08-26  75630.35  Marketing
6835  2021-08-26  79636.00  Marketing


Duplicate rows for ID 13a4ee07-a58a-4a2b-a249-8cec5e256e58:
                                        ID             Name   Age  \
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0
7276  13a4ee07-a58a-4a2b-a249-8cec5e256e58  Jennifer Taylor  26.0

                         Email   Join Date   Salary Department
7276  delgadojeffrey@yahoo.com  2022-06-08  62183.0         HR
7276  delgadojeffrey@yahoo.com  2022-03-16  62183.0         HR


Duplicate rows for ID 14452655-08d2-4698-8498-74f30a5e9f9f:
                                        ID     Name   Age               Email  \
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  unknown@domain.com
1877  14452655-08d2-4698-8498-74f30a5e9f9f  Unknown  57.0  unknown@domain.com

       Join Date     Salary Department
1877  1979-06-19  144339.00    Support
1877  2021-02-26  144311.66    Support


Duplicate rows for ID 144c46e8-f964-4374-96aa-ead07b754888:
                                        ID              Name   Age  \
3505  144c46e8-f964-4374-96aa-ead07b754888  Brandon Gonzalez  83.0
3505  144c46e8-f964-4374-96aa-ead07b754888  Brandon Gonzalez  83.0

                 Email   Join Date    Salary Department
3505  dawn30@gmail.com  1900-01-01  60280.00         HR
3505  dawn30@gmail.com  1900-01-01  51886.35         HR


Duplicate rows for ID 153493fc-efe1-4530-8b3d-7f2c2518796b:
                                        ID          Name   Age  \
9214  153493fc-efe1-4530-8b3d-7f2c2518796b  Megan Nguyen  83.0
9214  153493fc-efe1-4530-8b3d-7f2c2518796b  Megan Nguyen  83.0

                   Email   Join Date    Salary   Department
9214  unknown@domain.com  2020-02-18  92976.04  Engineering
9214  unknown@domain.com  2020-02-18  80220.00  Engineering


Duplicate rows for ID 15352b0d-8c4e-4f4d-a16b-9f94e62fe7af:
                                       ID       Name   Age  \
623  15352b0d-8c4e-4f4d-a16b-9f94e62fe7af  Amy Clark  48.0
623  15352b0d-8c4e-4f4d-a16b-9f94e62fe7af  Amy Clark  48.0

                    Email   Join Date   Salary   Department
623  jonessusan@gmail.com  2017-07-11  89347.0  Engineering
623  jonessusan@gmail.com  2023-04-23  89347.0  Engineering


Duplicate rows for ID 15f511c0-c77a-40e9-8cd5-90345022b847:
                                        ID          Name   Age  \
4045  15f511c0-c77a-40e9-8cd5-90345022b847  Amy Johnston  68.0
4045  15f511c0-c77a-40e9-8cd5-90345022b847  Amy Johnston  68.0

                 Email   Join Date     Salary Department
4045  anne74@yahoo.com  2006-05-30  120616.13         HR
4045  anne74@yahoo.com  2020-01-13  118299.00         HR


Duplicate rows for ID 162d1554-81c9-4ec2-9e07-e07372dbee99:
                                        ID                Name   Age  \
2543  162d1554-81c9-4ec2-9e07-e07372dbee99  Shannon Ryanothers  90.0
2543  162d1554-81c9-4ec2-9e07-e07372dbee99  Shannon Ryanothers  90.0

                   Email   Join Date   Salary Department
2543  unknown@domain.com  2021-12-24  45024.0    Support
2543  unknown@domain.com  2021-12-24  44944.5    Support


Duplicate rows for ID 1680e251-597a-4954-877a-789ce13e975d:
                                        ID               Name   Age  \
5430  1680e251-597a-4954-877a-789ce13e975d  William Hernandez  37.0
5430  1680e251-597a-4954-877a-789ce13e975d  William Hernandez  37.0

                     Email   Join Date    Salary Department

In [68]:
# converting Join Date to date format to compare the dates.
data['Join Date'] = pd.to_datetime(data['Join Date'], errors='coerce').dt.date

# Drop rows where 'Join Date' could not be converted
data = data.dropna(subset=['Join Date'])

# Sort data by ID and Join Date to ensure correct selection
data = data.sort_values(['ID', 'Join Date'], ascending=[True, False])

# Keep only the row with the most recent Join Date for each ID
data = data.drop_duplicates(subset=['ID'], keep='first')

In [69]:
data.shape

(8908, 7)

In [70]:
data['Age'].unique()

array([61., 88., 27., 74., 84., 43., 34., 25., 75., 54., 38., 46., 31.,
       22., 59., 37., 53., 64., 36., 83., 86., 40., 78., 26., 41., 47.,
       81., 50., 24., 60., 20., 82., 32., 80., 49., 57., 90., 45., 51.,
       73., 28., 66., 70., 68., 76., 19., 79., 62., 85., 69., 21., 52.,
       89., 55., 29., 42., 56., 58., 39., 63., 48., 33., 44., 72., 67.,
       35., 30., 77., 65., 18., 87., 71., 23.])

In [71]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8908 entries, 4626 to 7292
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          8908 non-null   object
 1   Name        8908 non-null   object
 2   Age         8908 non-null   float64
 3   Email       8908 non-null   object
 4   Join Date   8908 non-null   object
 5   Salary      8908 non-null   float64
 6   Department  8908 non-null   object
dtypes: float64(2), object(5)
memory usage: 556.8+ KB

In [72]:
unwanted_words = [
    "black", "cut", "without", "wind", "common", "time", "population", "reflect", "begin", "huge",
    "religious", "raise", "bad", "even", "Republican", "crease", "someone", "relate", "for", "sign",
    "body", "return", "threat", "contain", "establish", "focus", "half", "pick", "side",
    "quite", "police", "decade", "budget", "technology", "Congres", "animal", "voice", "unit", "land",
    "similar", "foot", "before", "your", "maintain", "provide", "record", "after", "audience", "les"
    , "agent", "maybe", "seat", "try", "listen", "physical", "trouble", "throw", "win", "under",
    "television", "discussion", "rich", "song", "must", "detail", "cold", "suffer", "explain",
    "significant", "let", "write", "could", "entire", "open", "herself", "understand", "him",
    "recognize", "interest", "research", "fine", "event", "whatever", "finish", "left", "within",
    "if", "prepare", "often", "leader", "have", "their", "life", "price", "customer", "property",
    "sense", "national", "toward", "star", "phone", "now", "develop", "morning", "dog", "door",
    "look", "during", "others", "particular", "stry", "nearly", "country", "western", "everybody",
    "night", "chair", "quickly", "visit", "radio", "meeting", "street", "investment", "issue", "rule",
    "really", "worker", "third", "game", "walk", "information", "short", "lead", "cultural", "cal",
    "main", "station", "create", "mount", "necessary", "former", "people", "behind", "marriage",
    "financial", "partner", "evidence", "start", "source", "capital", "of", "teach", "lawyer",
    "practice", "include", "white", "collection", "plant", "size", "mother", "form", "can", "ear",
    "effort", "indeed", "kitchen", "true", "popular", "spring", "cost", "paper", "appear", "item",
    "position", "ful", "word", "you", "end", "hotel", "action", "another", "outside", "row",
    "image", "community", "tyre", "cord", "bit", "watch", "season", "drive", "responsibility", "church",
    "thank", "make", "response", "stre", "carry", "party", "tre", "page", "almost", "place",
    "sister", "store", "learn", "stuf", "while", "score", "office", "day", "sometimes", "feel",
    "example", "billion", "car", "executive", "own", "compare", "sound", "about", "thing", "already",
    "husband", "raise", "fal", "many", "according", "whether", "low", "project", "together", "sport",
    "citizen", "per", "involve", "employe", "those", "mind", "training", "summer", "suggest", "couple",
    "help", "performance", "nothing", "happen", "smile", "this", "director", "how", "might", "meet",
    "member", "follow", "travel", "anyone", "through", "into", "name", "better", "affect", "everything",
    "realize", "second", "today", "wide", "late", "yet", "wear", "education", "claim", "surface",
    "protect", "effect", "wrong", "ground", "grow", "region", "away", "reduce", "firm", "five",
    "attention", "defense", "book", "bag", "child", "stage", "job", "act", "case", "something",
    "pattern", "news", "service", "deep", "send", "lose", "them", "way", "at", "they", "break",
    "real", "share", "politics", "else", "character", "various", "single", "state", "mine",
    "determine", "teacher", "memory", "whose", "management", "produce", "product", "risk", "federal",
    "bar", "hospital", "law", "east", "serious", "take", "since", "culture", "total", "peace",
    "policy", "instead", "blood", "seem", "machine", "likely", "reach", "arrive", "modern", "style",
    "ask", "area", "consumer", "candidate", "beautiful", "same", "force", "nice", "important",
    "whole", "model", "home", "strategy", "join", "scientist", "recently", "mention", "study", "wait",
    "behavior", "catch", "her", "author", "anything", "himself", "factor", "subject", "present",
    "direction", "represent", "large", "world", "college", "benefit", "admit", "professional", "guy",
    "mission", "offical", "should", "acros", "beyond", "town", "leave", "nation", "kid", "get",
    "consider", "player", "alone", "resource", "such", "throw", "economy", "thre", "others", "test",
    "idea", "send", "bil", "decide", "public", "situation", "activity", "interesting", "determine",
    "ago", "occur", "standard", "especially", "dream", "where", "suddenly", "feeling", "spend",
    "remain", "actually", "majority", "girl", "simple", "every", "different", "choice", "despite",
    "year", "key", "hard", "she", "but", "sure", "ward", "soon", "much", "the", "turn", "daughter",
    "forget", "when", "rise", "our", "security", "wonder", "deal", "parent", "option", "kind", "view",
    "heart", "TV", "operation", "why", "magazine", "strong", "thus", "care", "buy", "money", "agre",
    "water", "pm", "health", "inside", "push", "poor", "political", "fact", "each", "report",
    "statement", "campaign", "approach", "human", "middle", "everyone", "discus", "slate", "value",
    "certain", "attorney", "move", "red", "away", "fear", "long", "goal", "here", "list", "also",
    "camera", "rate", "hundred", "clear", "father", "institution", "parent", "argue", "painting",
    "keep", "military", "simply", "certainly", "speech", "mr", "back", "democratic", "yourself",
    "forward", "doctor", "task", "movement", "expert", "know", "brother", "organization", "rather",
    "city", "floor", "tonight", "lot", "charge", "center", "think", "fast", "out", "mis", "say",
    "civil", "however", "window", "manage", "from", "stock", "work", "with", "head", "medical",
    "group", "upon", "enough", "somebody", "room", "ready", "young", "usually", "once", "prove",
    "that", "drug", "fil", "analysis", "drop", "democrat", "proces", "amount", "government", "use",
    "board", "want", "its", "team", "agreement", "perhaps", "respond", "successful", "success",
    "among", "whom", "ever", "air", "against", "would", "energy", "concern", "war", "until", "hear",
    "society", "indicate", "food", "theory", "commercial", "fund", "offer", "impact", "wel", "past",
    "thought", "finally", "box", "southern", "smal", "measure", "month", "stop", "adult", "control",
    "administration", "easy", "experience", "crime", "personal", "itself", "some", "structure",
    "tend", "election", "just", "onto", "check", "either", "good", "sus","there", "music", 
    "coach", "right", "course", "port", "choose", "yeah", "program", "like",
    "bring", "because", "evening", "only", "above", "range", "very", "part", "leg", "act",
    "thousand", "field", "type", "play", "both", "several", "international", "degre", "trip",
    "able", "become", "put", "picture", "pas", "weight", "stop", "skil", "manager", "market",
    "talk", "minute", "oil", "result", "court", "gun", "not", "show", "challenge", "assume",
    "article", "value", "bring", "sper", "movement", "building", "between", "of", "exactly",
    "authority", "production", "specific", "conference", "west", "power", "best", "hair",
    "ability", "wife", "south", "worry", "receive", "order", "baby", "trial", "other",
    "pressure", "computer", "garden", "general", "professor", "house", "bed", "blue", "future",
    "view", "require", "sel", "radio", "trade", "them", "more", "enjoy", "change", "natural",
    "poor", "few", "tough", "serve", "possible", "rest", "down","official","hot","reveal"
]

# Compile regex pattern for unwanted words at the end of the last name
pattern = re.compile(r'(' + '|'.join(map(re.escape, unwanted_words)) + r')$', re.IGNORECASE)

# Function to clean names
def clean_name(name):
    match = re.match(r'(\w+)\s+(\w+)', name)
    if match:
        first_name = match.group(1).capitalize()
        last_name = match.group(2)
        last_name = pattern.sub('', last_name).strip()  # Remove unwanted word if present
        return f"{first_name} {last_name.capitalize()}" if last_name else first_name
    return name  # Return as is if no match

# Apply function to clean the 'name' column
data['Name'] = data['Name'].apply(clean_name)

In [73]:
# Detect Outliers using IQR for Salary
Q1 = data['Salary'].quantile(0.25)
Q3 = data['Salary'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = data[(data['Salary'] < lower_bound) | (data['Salary'] > upper_bound)]
print("Outliers in Salary:\n", outliers)

Outliers in Salary:
 Empty DataFrame
Columns: [ID, Name, Age, Email, Join Date, Salary, Department]
Index: []

In [74]:
# Detect Outliers using IQR for Age
Q1 = data['Age'].quantile(0.25)
Q3 = data['Age'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = data[(data['Age'] < lower_bound) | (data['Age'] > upper_bound)]
print("Outliers in Age:\n", outliers)

Outliers in Age:
 Empty DataFrame
Columns: [ID, Name, Age, Email, Join Date, Salary, Department]
Index: []

In [75]:
# Sort data by ID column in ascending order
data = data.sort_values(by="ID", ascending=True)

# Save the cleaned dataset
data.to_csv("cleaned_dataset.csv", index=False)